<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** A list of chat completion choices. Can be more than one if `n` is greater than 1 */
class Choice {
	use StringableTrait;

	/**
	 * @param int          $index         The index of the choice in the list of choices.
	 * @param Message      $message       A chat completion message generated by the model.
	 * @param FinishReason $finish_reason The reason the model stopped generating tokens.
	 */
	public function __construct(
		public readonly int $index,
		public readonly Message $message,
		public readonly FinishReason $finish_reason,
		public readonly ?bool $logprobs=null,
	) {
	}
}
