<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** Breakdown of tokens used in a completion. */
class CompletionTokenDetails {
	use StringableTrait;

	/**
	 * @param int $reasoning_tokens           Tokens generated by the model for reasoning.
	 * @param int $accepted_prediction_tokens When using Predicted Outputs, the number of tokens in the
	 *                                        prediction that appeared in the completion.
	 * @param int $rejected_prediction_tokens When using Predicted Outputs, the number of tokens in the
	 *                                        prediction that did not appear in the completion. However, like
	 *                                        reasoning tokens, these tokens are still counted in the total
	 *                                        completion tokens for purposes of billing, output, and context
	 *                                        window limits.
	 */
	public function __construct(
		public readonly int $reasoning_tokens,
		public readonly int $accepted_prediction_tokens,
		public readonly int $rejected_prediction_tokens,
	) {
	}
}
