<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** A chat completion message generated by the model. */
class Message {
	use StringableTrait;

	/** The contents of the message. */
	public readonly string $content;

	/**
	 * @param Role    $role    The role of the author of this message.
	 * @param ?string $refusal The refusal message generated by the model.
	 * @param ?string $content The contents of the message.
	 */
	public function __construct(
		public readonly Role $role,
		?string $refusal=null,
		?string $content=null,
	) {
		$this->content = $content ?? $refusal ?? 'No reply received.';
	}
}
