<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** A tool result message generated by us */
class ToolResultMessage extends Message {
	use StringableTrait;

	/**
	 * @param string $tool_call_id The call id for which is this the result
	 * @param string $content      The JSON-encoded result of the message
	 */
	public function __construct(
		public readonly string $tool_call_id,
		string $content,
	) {
		parent::__construct(role: Role::TOOL, content: $content);
	}
}
