<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** A list of tool call choices. Can be more than one if `n` is greater than 1 */
class ToolCallChoice {
	use StringableTrait;

	/**
	 * @param int             $index         The index of the choice in the list of choices.
	 * @param ToolCallMessage $message       A chat completion message generated by the model.
	 * @param FinishReason    $finish_reason The reason the model stopped generating tokens (always `"tool_calls"`).
	 */
	public function __construct(
		public readonly int $index,
		public readonly ToolCallMessage $message,
		public readonly FinishReason $finish_reason,
	) {
	}
}
