<?php declare(strict_types=1);

namespace Nadybot\Modules\AI_MODULE\Models;

use Nadybot\Core\StringableTrait;

/** A tool call message generated by the model. */
class ToolCallMessage {
	use StringableTrait;

	/**
	 * @param Role       $role       The role of the author of this message.
	 * @param ToolCall[] $tool_calls The tools to call
	 *
	 * @psalm-param list<ToolCall> $tool_calls
	 */
	public function __construct(
		public readonly Role $role,
		public array $tool_calls,
	) {
	}
}
