ARG PROXY_IMAGE=unstable
FROM quay.io/nadyita/aochatproxy:${PROXY_IMAGE} AS builder

FROM quay.io/nadyita/alpine:3.18
ARG VERSION

LABEL maintainer="nadyita@hodorraid.org" \
      description="self-sustaining docker image to run latest Nadybot, including AOChatProxy" \
      org.opencontainers.image.source="https://github.com/Nadybot/Nadybot"

ENTRYPOINT ["/sbin/tini", "-g", "--"]

CMD ["/nadybot/docker-entrypoint.sh"]

RUN apk --no-cache upgrade && \
    apk --no-cache add \
    php81-cli \
    php81-sqlite3 \
    php81-phar \
    php81-curl \
    php81-sockets \
    php81-pdo \
    php81-pdo_sqlite \
    php81-pdo_mysql \
    php81-mbstring \
    php81-ctype \
    php81-bcmath \
    php81-json \
    php81-posix \
    php81-simplexml \
    php81-dom \
    php81-gmp \
    php81-pcntl \
    php81-zip \
    php81-opcache \
    php81-fileinfo \
    php81-tokenizer \
    tini \
    jemalloc \
    sed \
    coreutils \
    && \
    adduser -h /nadybot -s /bin/false -D -H nadybot && \
    mkdir /proxy

COPY --chown=nadybot:nadybot . /nadybot
COPY --from=builder /aochatproxy /proxy/aochatproxy

ENV LD_PRELOAD=libjemalloc.so.2

RUN wget -O /usr/bin/composer https://getcomposer.org/composer-2.phar && \
    apk --no-cache add \
        sudo \
        jq \
    && \
    cd /nadybot && \
    sudo -u nadybot mkdir -p data/db cache && \
    sudo -u nadybot php81 /usr/bin/composer install --no-dev --no-interaction --no-progress -q && \
    sudo -u nadybot php81 /usr/bin/composer dumpautoload --no-dev --optimize --no-interaction 2>&1 | grep -v "/20[0-9]\{12\}_.*autoload" && \
    sudo -u nadybot php81 /usr/bin/composer clear-cache -q && \
    rm -f /usr/bin/composer && \
    jq 'del(.monolog.handlers.logs)|.monolog.formatters.console.options.format="[%level_name%] %message% %context% %extra%\n"|.monolog.formatters.console += {"calls": {"includeStacktraces": {"include" :true}}}' conf/logging.json > conf/logging.json.2 && \
    mv conf/logging.json.2 conf/logging.json && \
    chown nadybot:nadybot conf/logging.json && \
    chown nadybot /proxy && \
    chmod +x /proxy/aochatproxy && \
    apk del --no-cache sudo jq && \
    if [ "x${VERSION}" != "x" ]; then \
        sed -i -e "s/public const VERSION = \"[^\"]*\";/public const VERSION = \"${VERSION:-4.0}\";/g" src/Core/BotRunner.php; \
    fi && \
    sed -i -e 's/memory_limit = 128M/memory_limit = 192M/' /etc/php81/php.ini

USER nadybot

WORKDIR /nadybot
