php-version = "8.1"

[source]
paths = ["src"]
excludes = [
  "src/websetup",
   "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/.hidden/HiddenDirShouldBeIgnoredSniff.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/all_options.php",
  "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/.hidden/HiddenDirShouldBeIgnoredSniff.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/no_options.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/empty_options.php",
  "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/.hidden/HiddenDirShouldBeIgnoredSniff.php",
]
includes = ["vendor", "src/Core", "Stubs"]
extensions = ["php"]

[linter.rules]
#no-unused-parameter = { enabled = false }
loop-does-not-iterate  = { enabled = false }
#interface = { psr = false }
#class = { psr = false }
#no-assignment-in-condition = { enabled = false }
assert-description = { enabled = false }
prefer-arrow-function = { enabled = false }
no-error-control-operator = { enabled = false }
no-multi-assignments = { enabled = false }
excessive-parameter-list = { enabled = false }
too-many-properties = { enabled = false }
too-many-methods = { enabled = false }
kan-defect = { enabled = false }
halstead = { enabled = false }
cyclomatic-complexity = { enabled = false }
no-insecure-comparison = { enabled = false }
no-literal-password = { enabled = false }
no-empty-catch-clause = { enabled = false }
no-else-clause = { enabled = false }
#no-boolean-literal-comparison = { enabled = false }
#redundant-mathematical-operation = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
#dont-catch-error = { enabled = false }
literal-named-argument = { enabled = false }
#mixed-assignment = { enabled = false }
inline-variable-return = { enabled = false }
prefer-early-continue = { enabled = false }
no-nested-ternary = { enabled = false }
no-redundant-math = { enabled = false }
use-compound-assignment = { enabled = false }
tainted-data-to-sink = { enabled = false }
no-redundant-use = { enabled = false }
no-assign-in-condition = { enabled = false }
prefer-first-class-callable = { enabled = false }
too-many-enum-cases = { threshold = 666 }
no-sprintf-concat = { enabled = false }
no-redundant-method-override = { enabled = false }

[analyzer]
ignore = ["mixed-assignment", "mixed-argument", "redundant-docblock-type", "redundant-cast"]
