php_version = "8.1"

[source]
paths = ["src"]
excludes = [
  "src/Core/QueryBuilder.php"
]
includes = ["vendor", "src/Core"]
extensions = ["php"]

[linter]
default_plugins = true

[[linter.rules]]
name = "best-practices/no-unused-parameter"
level = "Off"

[[linter.rules]]
name = "best-practices/loop-does-not-iterate"
level = "Off"

[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "Off"

[[linter.rules]]
name = "strictness/require-constant-type"
level = "Off"

[[linter.rules]]
name = "strictness/missing-assert-description"
level = "Off"

[[linter.rules]]
name = "safety/no-suppressed-expression"
level = "Off"

[[linter.rules]]
name = "comment/docblock-syntax"
level = "Note"

[[linter.rules]]
name = "deprecation/optional-parameter-before-required"
level = "Off"

[[linter.rules]]
name = "best-practices/no-multi-assignments"
level = "Off"
