php_version = "8.1"

[source]
paths = ["src"]
excludes = [
  "src/websetup",
   "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/.hidden/HiddenDirShouldBeIgnoredSniff.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/all_options.php",
  "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/.hidden/HiddenDirShouldBeIgnoredSniff.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/no_options.php",
  "vendor/nikic/fast-route/test/HackTypechecker/fixtures/empty_options.php",
  "vendor/squizlabs/php_codesniffer/tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/.hidden/HiddenDirShouldBeIgnoredSniff.php",
]
includes = ["vendor", "src/Core"]
extensions = ["php"]

[linter]
default_plugins = true

[[linter.rules]]
name = "best-practices/no-unused-parameter"
level = "Off"

[[linter.rules]]
name = "best-practices/loop-does-not-iterate"
level = "Off"

[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "Off"

[[linter.rules]]
name = "strictness/missing-assert-description"
level = "Off"

[[linter.rules]]
name = "safety/no-suppressed-expression"
level = "Off"

[[linter.rules]]
name = "best-practices/no-multi-assignments"
level = "Off"

[[linter.rules]]
name = "maintainability/excessive-parameter-list"
level = "Off"

[[linter.rules]]
name = "maintainability/too-many-properties"
level = "Off"

[[linter.rules]]
name = "maintainability/too-many-methods"
level = "Off"

[[linter.rules]]
name = "maintainability/kan-defect"
level = "Off"

[[linter.rules]]
name = "maintainability/halstead"
level = "Off"

[[linter.rules]]
name = "maintainability/cyclomatic-complexity"
level = "Off"

[[linter.rules]]
name = "security/no-insecure-comparison"
level = "Off"

[[linter.rules]]
name = "security/no-literal-password"
level = "Off"

[[linter.rules]]
name = "best-practices/no-empty-catch-clause"
level = "Off"

[[linter.rules]]
name = "best-practices/no-else-clause"
level = "Off"

[[linter.rules]]
name = "best-practices/no-boolean-literal-comparison"
level = "Off"

[[linter.rules]]
name = "redundancy/redundant-mathematical-operation"
level = "Off"

[[linter.rules]]
name = "best-practices/no-boolean-flag-parameter"
level = "Off"

[[linter.rules]]
name = "best-practices/dont-catch-error"
level = "Off"

[[linter.rules]]
name = "best-practices/literal-named-argument"
level = "Off"

[[linter.rules]]
name = "mixed-assignment"
level = "Off"
