<?php declare(strict_types=1);

namespace Nadybot\Core\Types;

use ValueError;

enum Playfield: int {
	/** @var array<string,string|int|null> */
	public const EXAMPLE_TOKENS = [
		'pf-id' => 551,
		'pf-long' => 'Wailing Wastes',
		'pf-short' => 'WW',
	];

	/** @return array<string,string|int|null> */
	public function getTokens(): array {
		return [
			'pf-id' => $this->value,
			'pf-long' => $this->long(),
			'pf-short' => $this->short(),
		];
	}

	public static function getShortRegexp(): string {
		return implode('|', [
			'ABAN',
			'ADO',
			'ADOCITY',
			'AEG',
			'AND',
			'APFHUB',
			'ARETE',
			'AS',
			'AV',
			'BF',
			'BOR',
			'BS',
			'INFMARSHES',
			'CAMA',
			'CAMELOT',
			'CAMAS',
			'CAV',
			'CLON',
			'CP',
			'CT',
			'DALJA',
			'DALJAS',
			'DANTES',
			'DAV',
			'EFP',
			'ELYEAST',
			'ELY',
			'ELYNORTH',
			'ELYSOUTH',
			'ELYWEST',
			'ENEL',
			'ENELS',
			'FGRID',
			'4HO',
			'GALAH',
			'GALAHS',
			'GC',
			'GS',
			'GILTHAR',
			'GILTHARS',
			'GOF',
			'GTC',
			'GRID',
			'HITW',
			'HWO',
			'ISP',
			'INF',
			'HARBOR',
			'MARKET',
			'PLATFORM',
			'PLAZA',
			'RESEARCH',
			'JY',
			'LOXHUB',
			'LF',
			'MACCIS',
			'MW',
			'MINES-LVL30',
			'MINES-LVL60',
			'MINES-LVL100',
			'MINES-LVL150',
			'MINES-LVL200',
			'MINES-LVL214',
			'MINES-LVL220',
			'MORDETH',
			'MORDETHS',
			'MORT',
			'MD',
			'NASCFRONT',
			'NASCSWAMP',
			'NASCWILDS',
			'NC',
			'NLD',
			'NL',
			'OCRA',
			'OCRAS',
			'OA',
			'ENT',
			'OF',
			'OHQ',
			'OT',
			'ANTENORA',
			'CAINA',
			'JUDECCA',
			'PTOLEMEA',
			'PCT',
			'PENFOREST',
			'PENHOLLOW',
			'PENVALLEY',
			'PW',
			'PM',
			'ROCH',
			'ROCHS',
			'RB',
			'RG',
			'RR',
			'SCHEOLLOWER',
			'SCHEOLUPPER',
			'S13',
			'S28',
			'S35',
			'SHERE',
			'SHERES',
			'SMUGDEN',
			'SAV',
			'SFH',
			'SEB',
			'SWB',
			'TLR',
			'TR',
			'THRAK',
			'3CE',
			'3CW',
			'TC',
			'TIR',
			'UNICORNHUB',
			'APFHUB',
			'UNKNWN',
			'USEB',
			'UC',
			'UF',
			'VANYA',
			'VANYAS',
			'VW',
			'WW',
			'WV',
			'WA',
		]);
	}

	public static function getNameRegexp(): string {
		return implode('|', [
			'4 holes',
			'andromeda',
			'aegean',
			'old athen',
			'athen shire',
			'west athens',
			'avalon',
			'belial forest',
			'borealis',
			'broken shores',
			'central artery valley',
			'clondyke',
			'coast of peace',
			'coast of tranquility',
			'deep artery valley',
			'eastern fouls plain',
			'eastern foul plain',
			'galway county',
			'galway shire',
			'greater omni forest',
			'greater tir county',
			'holes in the wall',
			'lush fields',
			'milky way', 'milkyway',
			'mutant domain',
			'newland',
			'newland city',
			'newland desert',
			'omni forest',
			'omni-1 entertainment',
			'omni-1 ent',
			'omni ent',
			'omnient',
			'omni-1 hq',
			'omni hq',
			'omnihq',
			'omni-1 trade',
			'omni trade',
			'omnitrade',
			'perpetual wastelands',
			'pleasant meadows',
			'rome blue',
			'rome green',
			'rome red',
			'southern artery valley',
			'southern fouls hills',
			'stret east bank',
			'stret west bank',
			'the longest road',
			'the reck',
			'reck',
			'tir',
			'tir county',
			'upper stret east bank',
			'varmint woods',
			'wailing wastes',
			'wartorn valley',
			'holoworld: omni training',
			'omni training',
			'holoworld',
			'park: clan training',
			'clan training',
			'park',
			'junkyard: neutral training',
			'neutral training',
			'junkyard',
			'icc shuttleport',
			'shuttleport',
			'uturn canyon',
			'uturn forest',
			'three craters east',
			'three craters west',
			'arete',
			'unicorn outpost',
			'adonis city',
			'ado city',
			'adocity',
			'adonis abyss',
			'ado abyss',
			'elysium',
			'elysium east',
			'elysium e',
			'elysium north',
			'elysium n',
			'elysium south',
			'elysium s',
			'elysium west',
			'elysium w',
			'inferno',
			'inferno burning marshes',
			'burning marshes',
			'marshes',
			'jobe harbor',
			'jobe market',
			'jobe platform',
			'jobe plaza',
			'jobe research',
			'nascense frontier',
			'nascense swamp',
			'nascense wilds',
			'penumbra forest',
			'penumbra hollow',
			'penumbra valley',
			'pandemonium antenora',
			'antenora',
			'pandemonium caina',
			'caina',
			'pandemonium judecca',
			'judecca',
			'pandemonium ptolemea',
			'ptolemea',
			'scheol upper',
			'upper scheol',
			'scheol lower',
			'lower scheol',
			'unicorn defence hub',
			'unicorn hub',
			'unicornhub',
			'lox hub',
			'loxhub',
			'sbc-xpm site alpha-romeo 21',
			'alpha-romeo 21',
			'sbc-xpm 21',
			'sbc-xpm site alpha-romeo 22',
			'alpha-romeo 22',
			'sbc-xpm 22',
			'sbc-xpm site alpha-romeo 23',
			'alpha-romeo 23',
			'sbc-xpm 23',
			'sbc-xpm site alpha-romeo 24',
			'alpha-romeo 24',
			'sbc-xpm 24',
			'sbc-xpm site alpha-romeo 25',
			'alpha-romeo 25',
			'sbc-xpm 25',
			'sbc-xpm site alpha-romeo 26',
			'alpha-romeo 26',
			'sbc-xpm 26',
			'sbc-xpm site alpha-romeo 27',
			'alpha-romeo 27',
			'sbc-xpm 27',
			'4ho',
			'and',
			'aeg',
			'oa',
			'as',
			'wa',
			'av',
			'bf',
			'bor',
			'bs',
			'cav',
			'clon',
			'cp',
			'ct',
			'dav',
			'efp',
			'gc',
			'gs',
			'gof',
			'gtc',
			'hitw',
			'lf',
			'mw',
			'mort',
			'md',
			'nl',
			'nc',
			'nld',
			'of',
			'ent',
			'ohq',
			'ot',
			'pw',
			'pm',
			'rb',
			'rg',
			'rr',
			'sav',
			'sfh',
			'seb',
			'swb',
			'tlr',
			'tr',
			'tc',
			'useb',
			'vw',
			'ww',
			'wv',
			'hwo',
			'pct',
			'jy',
			'isp',
			'uc',
			'uf',
			'3ce',
			'3cw',
			'apfhub',
			'ado',
			'ely',
			'elyeast',
			'elynorth',
			'elysouth',
			'elywest',
			'inf',
			'infmarshes',
			'harbor',
			'market',
			'platform',
			'plaza',
			'research',
			'nascfrontier',
			'nascswamp',
			'nascwilds',
			'penforest',
			'penhollow',
			'penvalley',
			'pandeantenora',
			'pandecaina',
			'pandejudecca',
			'pandeptolemea',
			'mines-lvl30',
			'mines-lvl60',
			'mines-lvl100',
			'mines-lvl150',
			'mines-lvl200',
			'mines-lvl214',
			'mines-lvl220',
			'roch',
			'aban',
			'fgrid',
			'smugden',
			'grid',
			's13',
			's28',
			's35',
			'apfs',
			'thrak',
			'enel',
			'enels',
			'shere',
			'sheres',
			'ocra',
			'gilthar',
			'gilthars',
			'dalja',
			'daljas',
			'camelot',
			'cama',
			'camas',
			'vanya',
			'vanyas',
			'galah',
			'galahs',
			'mordeth',
			'mordeths',
			'dantes',
			'maccis',
			'ocras',
			'rochs',
		]);
	}

	/**
	 * Try to guess the Playfield by its short or long name
	 *
	 * @throws ValueError for illegal names
	 */
	public static function byName(string $name): self {
		return match (strtolower($name)) {
			'4 holes' => self::FourHoles,
			'andromeda' => self::Andromeda,
			'aegean' => self::Aegean,
			'old athen' => self::OldAthen,
			'athen shire' => self::AthenShire,
			'west athens' => self::WestAthens,
			'avalon' => self::Avalon,
			'belial forest' => self::BelialForest,
			'borealis' => self::Borealis,
			'broken shores' => self::BrokenShores,
			'central artery valley' => self::CentralArteryValley,
			'clondyke' => self::Clondyke,
			'coast of peace' => self::CoastOfPeace,
			'coast of tranquility' => self::CoastOfTranquility,
			'deep artery valley' => self::DeepArteryValley,
			'eastern fouls plain' => self::EasternFoulsPlain,
			'eastern foul plain' => self::EasternFoulsPlain,
			'galway county' => self::GalwayCounty,
			'galway shire' => self::GalwayShire,
			'greater omni forest' => self::GreaterOmniForest,
			'greater tir county' => self::GreaterTirCounty,
			'holes in the wall' => self::HolesInTheWall,
			'lush fields' => self::LushFields,
			'milky way','milkyway' => self::MilkyWay,
			'mutant domain' => self::MutantDomain,
			'newland' => self::Newland,
			'newland city' => self::NewlandCity,
			'newland desert' => self::NewlandDesert,
			'omni forest' => self::OmniForest,
			'omni-1 entertainment',
			'omni-1 ent',
			'omni ent',
			'omnient' => self::OmniEnt,
			'omni-1 hq',
			'omni hq',
			'omnihq' => self::OmniHQ,
			'omni-1 trade',
			'omni trade',
			'omnitrade' => self::OmniTrade,
			'perpetual wastelands' => self::PerpetualWastelands,
			'pleasant meadows' => self::PleasantMeadows,
			'rome blue' => self::RomeBlue,
			'rome green' => self::RomeGreen,
			'rome red' => self::RomeRed,
			'southern artery valley' => self::SouthernArteryValley,
			'southern fouls hills' => self::SouthernFoulsHills,
			'stret east bank' => self::StretEastBank,
			'stret west bank' => self::StretWestBank,
			'the longest road' => self::TheLongestRoad,
			'the reck',
			'reck' => self::TheReck,
			'tir' => self::Tir,
			'tir county' => self::TirCounty,
			'upper stret east bank' => self::UpperStretEastBank,
			'varmint woods' => self::VarmintWoods,
			'wailing wastes' => self::WailingWastes,
			'wartorn valley' => self::WartornValley,
			'holoworld: omni training',
			'omni training',
			'holoworld' => self::HoloworldOmniTraining,
			'park: clan training',
			'clan training',
			'park' => self::ParkClanTraining,
			'junkyard: neutral training',
			'neutral training',
			'junkyard' => self::JunkyardNeutralTraining,
			'icc shuttleport',
			'shuttleport' => self::ICCShuttleport,
			'uturn canyon' => self::UturnCanyon,
			'uturn forest' => self::UturnForest,
			'three craters east' => self::ThreeCratersEast,
			'three craters west' => self::ThreeCratersWest,
			'arete' => self::Arete,
			'unicorn outpost' => self::UnicornOutpost,
			'adonis city',
			'ado city',
			'adocity' => self::AdonisCity,
			'adonis abyss',
			'ado abyss' => self::AdonisAbyss,
			'elysium' => self::Elysium,
			'elysium east',
			'elysium e' => self::ElysiumEast,
			'elysium north',
			'elysium n' => self::ElysiumNorth,
			'elysium south',
			'elysium s' => self::ElysiumSouth,
			'elysium west',
			'elysium w' => self::ElysiumWest,
			'inferno' => self::Inferno,
			'inferno burning marshes',
			'burning marshes',
			'marshes' => self::BurningMarshes,
			'jobe harbor' => self::JobeHarbor,
			'jobe market' => self::JobeMarket,
			'jobe platform' => self::JobePlatform,
			'jobe plaza' => self::JobePlaza,
			'jobe research' => self::JobeResearch,
			'nascense frontier' => self::NascenseFrontier,
			'nascense swamp' => self::NascenseSwamp,
			'nascense wilds' => self::NascenseWilds,
			'penumbra forest' => self::PenumbraForest,
			'penumbra hollow' => self::PenumbraHollow,
			'penumbra valley' => self::PenumbraValley,
			'pandemonium antenora',
			'antenora' => self::PandemoniumAntenora,
			'pandemonium caina',
			'caina' => self::PandemoniumCaina,
			'pandemonium judecca',
			'judecca' => self::PandemoniumJudecca,
			'pandemonium ptolemea',
			'ptolemea' => self::PandemoniumPtolemea,
			'scheol upper',
			'upper scheol' => self::ScheolUpper,
			'scheol lower',
			'lower scheol' => self::ScheolLower,
			'unicorn defence hub',
			'unicorn hub',
			'unicornhub' => self::UnicornDefenceHub,
			'lox hub',
			'loxhub' => self::LoxHub,
			'sbc-xpm site alpha-romeo 21',
			'alpha-romeo 21',
			'sbc-xpm 21' => self::MinesLvl30,
			'sbc-xpm site alpha-romeo 22',
			'alpha-romeo 22',
			'sbc-xpm 22' => self::MinesLvl60,
			'sbc-xpm site alpha-romeo 23',
			'alpha-romeo 23',
			'sbc-xpm 23' => self::MinesLvl100,
			'sbc-xpm site alpha-romeo 24',
			'alpha-romeo 24',
			'sbc-xpm 24' => self::MinesLvl150,
			'sbc-xpm site alpha-romeo 25',
			'alpha-romeo 25',
			'sbc-xpm 25' => self::MinesLvl200,
			'sbc-xpm site alpha-romeo 26',
			'alpha-romeo 26',
			'sbc-xpm 26' => self::MinesLvl214,
			'sbc-xpm site alpha-romeo 27',
			'alpha-romeo 27',
			'sbc-xpm 27' => self::MinesLvl220,
			'4ho' => self::FourHoles,
			'and' => self::Andromeda,
			'aeg' => self::Aegean,
			'oa' => self::OldAthen,
			'as' => self::AthenShire,
			'wa' => self::WestAthens,
			'av' => self::Avalon,
			'bf' => self::BelialForest,
			'bor' => self::Borealis,
			'bs' => self::BrokenShores,
			'cav' => self::CentralArteryValley,
			'clon' => self::Clondyke,
			'cp' => self::CoastOfPeace,
			'ct' => self::CoastOfTranquility,
			'dav' => self::DeepArteryValley,
			'efp' => self::EasternFoulsPlain,
			'gc' => self::GalwayCounty,
			'gs' => self::GalwayShire,
			'gof' => self::GreaterOmniForest,
			'gtc' => self::GreaterTirCounty,
			'hitw' => self::HolesInTheWall,
			'lf' => self::LushFields,
			'mw' => self::MilkyWay,
			'mort' => self::Mort,
			'md' => self::MutantDomain,
			'nl' => self::Newland,
			'nc' => self::NewlandCity,
			'nld' => self::NewlandDesert,
			'of' => self::OmniForest,
			'ent' => self::OmniEnt,
			'ohq' => self::OmniHQ,
			'ot' => self::OmniTrade,
			'pw' => self::PerpetualWastelands,
			'pm' => self::PleasantMeadows,
			'rb' => self::RomeBlue,
			'rg' => self::RomeGreen,
			'rr' => self::RomeRed,
			'sav' => self::SouthernArteryValley,
			'sfh' => self::SouthernFoulsHills,
			'seb' => self::StretEastBank,
			'swb' => self::StretWestBank,
			'tlr' => self::TheLongestRoad,
			'tr' => self::TheReck,
			'tc' => self::TirCounty,
			'useb' => self::UpperStretEastBank,
			'vw' => self::VarmintWoods,
			'ww' => self::WailingWastes,
			'wv' => self::WartornValley,
			'hwo' => self::HoloworldOmniTraining,
			'pct' => self::ParkClanTraining,
			'jy' => self::JunkyardNeutralTraining,
			'isp' => self::ICCShuttleport,
			'uc' => self::UturnCanyon,
			'uf' => self::UturnForest,
			'3ce' => self::ThreeCratersEast,
			'3cw' => self::ThreeCratersWest,
			'apfhub' => self::UnicornOutpost,
			'ado' => self::AdonisAbyss,
			'ely' => self::Elysium,
			'elyeast' => self::ElysiumEast,
			'elynorth' => self::ElysiumNorth,
			'elysouth' => self::ElysiumSouth,
			'elywest' => self::ElysiumWest,
			'inf' => self::Inferno,
			'infmarshes' => self::BurningMarshes,
			'harbor' => self::JobeHarbor,
			'market' => self::JobeMarket,
			'platform' => self::JobePlatform,
			'plaza' => self::JobePlaza,
			'research' => self::JobeResearch,
			'nascfrontier' => self::NascenseFrontier,
			'nascswamp' => self::NascenseSwamp,
			'nascwilds' => self::NascenseWilds,
			'penforest' => self::PenumbraForest,
			'penhollow' => self::PenumbraHollow,
			'penvalley' => self::PenumbraValley,
			'pandeantenora' => self::PandemoniumAntenora,
			'pandecaina' => self::PandemoniumCaina,
			'pandejudecca' => self::PandemoniumJudecca,
			'pandeptolemea' => self::PandemoniumPtolemea,
			'mines-lvl30' => self::MinesLvl30,
			'mines-lvl60' => self::MinesLvl60,
			'mines-lvl100' => self::MinesLvl100,
			'mines-lvl150' => self::MinesLvl150,
			'mines-lvl200' => self::MinesLvl200,
			'mines-lvl214' => self::MinesLvl214,
			'mines-lvl220' => self::MinesLvl220,
			'roch' => self::RochGarden,
			'aban' => self::AbanGarden,
			'fgrid' => self::FixerGrid,
			'smugden' => self::SmugglersDen,
			'grid' => self::Grid,
			's13' => self::Sector13,
			's28' => self::Sector28,
			's35' => self::Sector35,
			'apfs' => self::APFHub,
			'thrak' => self::ThrakGarden,
			'enel' => self::EnelGarden,
			'enels' => self::EnelsSanctuary,
			'shere' => self::ShereGarden,
			'sheres' => self::SheresSanctuary,
			'ocra' => self::OcraGarden,
			'gilthar' => self::GiltharGarden,
			'gilthars' => self::GiltharsSanctuary,
			'dalja' => self::DaljaGarden,
			'daljas' => self::DaljasSanctuary,
			'camelot' => self::Camelot,
			'cama' => self::CamaGarden,
			'camas' => self::CamasSanctuary,
			'vanya' => self::VanyaGarden,
			'vanyas' => self::VanyasSanctuary,
			'galah' => self::GalahadGarden,
			'galahs' => self::GalahadsSanctuary,
			'mordeth' => self::MordethGarden,
			'mordeths' => self::MordethsSanctuary,
			'dantes' => self::DantesSanctuary,
			'maccis' => self::MacciavellisSanctuary,
			'ocras' => self::OcrasSanctuary,
			'rochs' => self::RochsSanctuary,
			default => throw new ValueError("\"{$name}\" is not a valid backing value for eum \"Playfield\""),
		};
	}

	public static function tryByName(string $name): ?self {
		try {
			return self::byName($name);
		} catch (ValueError) {
			return null;
		}
	}

	public function long(): string {
		/** @psalm-suppress UnhandledMatchCondition: */
		return match ($this) {
			self::AbanGarden => 'The Garden of Aban',
			self::AdonisAbyss => 'Adonis Abyss',
			self::AdonisCity => 'Adonis City',
			self::Aegean => 'Aegean',
			self::Andromeda => 'Andromeda',
			self::APFHub => 'APF Hub',
			self::Arete => 'Arete',
			self::AthenShire => 'Athen Shire',
			self::Avalon => 'Avalon',
			self::BelialForest => 'Belial Forest',
			self::Borealis => 'Borealis',
			self::BrokenShores => 'Broken Shores',
			self::BurningMarshes => 'Inferno Burning Marshes',
			self::CamaGarden => 'The Garden of Cama',
			self::Camelot => 'Camelot',
			self::CamasSanctuary => 'Camas Sanctuary',
			self::CentralArteryValley => 'Central Artery Valley',
			self::Clondyke => 'Clondyke',
			self::CoastOfPeace => 'Coast of Peace',
			self::CoastOfTranquility => 'Coast of Tranquility',
			self::DaljaGarden => 'The Garden of Dalja',
			self::DaljasSanctuary => 'Daljas Sanctuary',
			self::DantesSanctuary => 'Dantes Sanctuary',
			self::DeepArteryValley => 'Deep Artery Valley',
			self::EasternFoulsPlain => 'Eastern Fouls Plain',
			self::ElysiumEast => 'Elysium East',
			self::Elysium => 'Elysium',
			self::ElysiumNorth => 'Elysium North',
			self::ElysiumSouth => 'Elysium South',
			self::ElysiumWest => 'Elysium West',
			self::EnelGarden => 'The Garden of Enel',
			self::EnelsSanctuary => 'Enels Sanctuary',
			self::FixerGrid => 'Fixer Grid',
			self::FourHoles => '4 Holes',
			self::GalahadGarden => 'The Garden of Lord Galahad',
			self::GalahadsSanctuary => 'Lord Galahads Sanctuary',
			self::GalwayCounty => 'Galway County',
			self::GalwayShire => 'Galway Shire',
			self::GiltharGarden => 'The Garden of Gilthar',
			self::GiltharsSanctuary => 'Gilthars Sanctuary',
			self::GreaterOmniForest => 'Greater Omni Forest',
			self::GreaterTirCounty => 'Greater Tir County',
			self::Grid => 'Grid',
			self::HolesInTheWall => 'Holes in the Wall',
			self::HoloworldOmniTraining => 'Holoworld: Omni Training',
			self::ICCShuttleport => 'ICC Shuttleport',
			self::Inferno => 'Inferno',
			self::JobeHarbor => 'Jobe Harbor',
			self::JobeMarket => 'Jobe Market',
			self::JobePlatform => 'Jobe Platform',
			self::JobePlaza => 'Jobe Plaza',
			self::JobeResearch => 'Jobe Research',
			self::JunkyardNeutralTraining => 'Junkyard: Neutral Training',
			self::LoxHub => 'LoX Hub',
			self::LushFields => 'Lush Fields',
			self::MacciavellisSanctuary => 'Macciavellis Sanctuary',
			self::MilkyWay => 'Milky Way',
			self::MinesLvl30 => 'SBC-Xpm Site Alpha-Romeo 21',
			self::MinesLvl60 => 'SBC-Xpm Site Alpha-Romeo 22',
			self::MinesLvl100 => 'SBC-Xpm Site Alpha-Romeo 23',
			self::MinesLvl150 => 'SBC-Xpm Site Alpha-Romeo 24',
			self::MinesLvl200 => 'SBC-Xpm Site Alpha-Romeo 25',
			self::MinesLvl214 => 'SBC-Xpm Site Alpha-Romeo 26',
			self::MinesLvl220 => 'SBC-Xpm Site Alpha-Romeo 27',
			self::MordethGarden => 'The Garden of Lord Mordeth',
			self::MordethsSanctuary => 'Lord Mordeths Sanctuary',
			self::Mort => 'Mort',
			self::MutantDomain => 'Mutant Domain',
			self::NascenseFrontier => 'Nascense Frontier',
			self::NascenseSwamp => 'Nascense Swamp',
			self::NascenseWilds => 'Nascense Wilds',
			self::NewlandCity => 'Newland City',
			self::NewlandDesert => 'Newland Desert',
			self::Newland => 'Newland',
			self::OcraGarden => 'The Garden of Ocra',
			self::OcrasSanctuary => 'Ocras Sanctuary',
			self::OldAthen => 'Old Athen',
			self::OmniEnt => 'Omni-1 Entertainment',
			self::OmniForest => 'Omni Forest',
			self::OmniHQ => 'Omni-1 HQ',
			self::OmniTrade => 'Omni-1 Trade',
			self::PandemoniumAntenora => 'Pandemonium Antenora',
			self::PandemoniumCaina => 'Pandemonium Caina',
			self::PandemoniumJudecca => 'Pandemonium Judecca',
			self::PandemoniumPtolemea => 'Pandemonium Ptolemea',
			self::ParkClanTraining => 'Park: Clan Training',
			self::PenumbraForest => 'Penumbra Forest',
			self::PenumbraHollow => 'Penumbra Hollow',
			self::PenumbraValley => 'Penumbra Valley',
			self::PerpetualWastelands => 'Perpetual Wastelands',
			self::PleasantMeadows => 'Pleasant Meadows',
			self::RochGarden => 'The Garden of Roch',
			self::RochsSanctuary => 'Rochs Sanctuary',
			self::RomeBlue => 'Rome Blue',
			self::RomeGreen => 'Rome Green',
			self::RomeRed => 'Rome Red',
			self::ScheolLower => 'Scheol Lower',
			self::ScheolUpper => 'Scheol Upper',
			self::Sector13 => 'Sector 13',
			self::Sector28 => 'Sector 28',
			self::Sector35 => 'Sector 35',
			self::ShereGarden => 'The Garden of Shere',
			self::SheresSanctuary => 'Sheres Sanctuary',
			self::SmugglersDen => 'Smuggler\'s Den',
			self::SouthernArteryValley => 'Southern Artery Valley',
			self::SouthernFoulsHills => 'Southern Fouls Hills',
			self::StretEastBank => 'Stret East Bank',
			self::StretWestBank => 'Stret West Bank',
			self::TheLongestRoad => 'The Longest Road',
			self::TheReck => 'The Reck',
			self::ThrakGarden => 'The Garden of Thrak',
			self::ThreeCratersEast => 'Three Craters East',
			self::ThreeCratersWest => 'Three Craters West',
			self::TirCounty => 'Tir County',
			self::Tir => 'Tir',
			self::UnicornDefenceHub => 'Unicorn Defence Hub',
			self::UnicornOutpost => 'Unicorn Outpost',
			self::Unknown => 'Unknown playfield or instance',
			self::UpperStretEastBank => 'Upper Stret East Bank',
			self::UturnCanyon => 'Uturn Canyon',
			self::UturnForest => 'Uturn Forest',
			self::VanyaGarden => 'The Garden of Vanya',
			self::VanyasSanctuary => 'Vanyas Sanctuary',
			self::VarmintWoods => 'Varmint Woods',
			self::WailingWastes => 'Wailing Wastes',
			self::WartornValley => 'Wartorn Valley',
			self::WestAthens => 'West Athens',
		};
	}

	public function short(): string {
		/** @psalm-suppress UnhandledMatchCondition: */
		return match ($this) {
			self::AbanGarden => 'ABAN',
			self::AdonisAbyss => 'ADO',
			self::AdonisCity => 'ADOCITY',
			self::Aegean => 'AEG',
			self::Andromeda => 'AND',
			self::APFHub => 'APFHUB',
			self::Arete => 'ARETE',
			self::AthenShire => 'AS',
			self::Avalon => 'AV',
			self::BelialForest => 'BF',
			self::Borealis => 'BOR',
			self::BrokenShores => 'BS',
			self::BurningMarshes => 'INFMARSHES',
			self::CamaGarden => 'CAMA',
			self::Camelot => 'CAMELOT',
			self::CamasSanctuary => 'CAMAS',
			self::CentralArteryValley => 'CAV',
			self::Clondyke => 'CLON',
			self::CoastOfPeace => 'CP',
			self::CoastOfTranquility => 'CT',
			self::DaljaGarden => 'DALJA',
			self::DaljasSanctuary => 'DALJAS',
			self::DantesSanctuary => 'DANTES',
			self::DeepArteryValley => 'DAV',
			self::EasternFoulsPlain => 'EFP',
			self::ElysiumEast => 'ELYEAST',
			self::Elysium => 'ELY',
			self::ElysiumNorth => 'ELYNORTH',
			self::ElysiumSouth => 'ELYSOUTH',
			self::ElysiumWest => 'ELYWEST',
			self::EnelGarden => 'ENEL',
			self::EnelsSanctuary => 'ENELS',
			self::FixerGrid => 'FGRID',
			self::FourHoles => '4HO',
			self::GalahadGarden => 'GALAH',
			self::GalahadsSanctuary => 'GALAHS',
			self::GalwayCounty => 'GC',
			self::GalwayShire => 'GS',
			self::GiltharGarden => 'GILTHAR',
			self::GiltharsSanctuary => 'GILTHARS',
			self::GreaterOmniForest => 'GOF',
			self::GreaterTirCounty => 'GTC',
			self::Grid => 'GRID',
			self::HolesInTheWall => 'HITW',
			self::HoloworldOmniTraining => 'HWO',
			self::ICCShuttleport => 'ISP',
			self::Inferno => 'INF',
			self::JobeHarbor => 'HARBOR',
			self::JobeMarket => 'MARKET',
			self::JobePlatform => 'PLATFORM',
			self::JobePlaza => 'PLAZA',
			self::JobeResearch => 'RESEARCH',
			self::JunkyardNeutralTraining => 'JY',
			self::LoxHub => 'LOXHUB',
			self::LushFields => 'LF',
			self::MacciavellisSanctuary => 'MACCIS',
			self::MilkyWay => 'MW',
			self::MinesLvl30 => 'MINES-LVL30',
			self::MinesLvl60 => 'MINES-LVL60',
			self::MinesLvl100 => 'MINES-LVL100',
			self::MinesLvl150 => 'MINES-LVL150',
			self::MinesLvl200 => 'MINES-LVL200',
			self::MinesLvl214 => 'MINES-LVL214',
			self::MinesLvl220 => 'MINES-LVL220',
			self::MordethGarden => 'MORDETH',
			self::MordethsSanctuary => 'MORDETHS',
			self::Mort => 'MORT',
			self::MutantDomain => 'MD',
			self::NascenseFrontier => 'NASCFRONT',
			self::NascenseSwamp => 'NASCSWAMP',
			self::NascenseWilds => 'NASCWILDS',
			self::NewlandCity => 'NC',
			self::NewlandDesert => 'NLD',
			self::Newland => 'NL',
			self::OcraGarden => 'OCRA',
			self::OcrasSanctuary => 'OCRAS',
			self::OldAthen => 'OA',
			self::OmniEnt => 'ENT',
			self::OmniForest => 'OF',
			self::OmniHQ => 'OHQ',
			self::OmniTrade => 'OT',
			self::PandemoniumAntenora => 'ANTENORA',
			self::PandemoniumCaina => 'CAINA',
			self::PandemoniumJudecca => 'JUDECCA',
			self::PandemoniumPtolemea => 'PTOLEMEA',
			self::ParkClanTraining => 'PCT',
			self::PenumbraForest => 'PENFOREST',
			self::PenumbraHollow => 'PENHOLLOW',
			self::PenumbraValley => 'PENVALLEY',
			self::PerpetualWastelands => 'PW',
			self::PleasantMeadows => 'PM',
			self::RochGarden => 'ROCH',
			self::RochsSanctuary => 'ROCHS',
			self::RomeBlue => 'RB',
			self::RomeGreen => 'RG',
			self::RomeRed => 'RR',
			self::ScheolLower => 'SCHEOLLOWER',
			self::ScheolUpper => 'SCHEOLUPPER',
			self::Sector13 => 'S13',
			self::Sector28 => 'S28',
			self::Sector35 => 'S35',
			self::ShereGarden => 'SHERE',
			self::SheresSanctuary => 'SHERES',
			self::SmugglersDen => 'SMUGDEN',
			self::SouthernArteryValley => 'SAV',
			self::SouthernFoulsHills => 'SFH',
			self::StretEastBank => 'SEB',
			self::StretWestBank => 'SWB',
			self::TheLongestRoad => 'TLR',
			self::TheReck => 'TR',
			self::ThrakGarden => 'THRAK',
			self::ThreeCratersEast => '3CE',
			self::ThreeCratersWest => '3CW',
			self::TirCounty => 'TC',
			self::Tir => 'TIR',
			self::UnicornDefenceHub => 'UNICORNHUB',
			self::UnicornOutpost => 'APFHUB',
			self::Unknown => 'UNKNWN',
			self::UpperStretEastBank => 'USEB',
			self::UturnCanyon => 'UC',
			self::UturnForest => 'UF',
			self::VanyaGarden => 'VANYA',
			self::VanyasSanctuary => 'VANYAS',
			self::VarmintWoods => 'VW',
			self::WailingWastes => 'WW',
			self::WartornValley => 'WV',
			self::WestAthens => 'WA',
		};
	}

	case Unknown = 0;
	case Camelot = 120;
	case SmugglersDen = 123;
	case Grid = 152;
	case Avalon = 505;
	case OldAthen = 540;
	case WestAthens = 545;
	case AthenShire = 550;
	case WailingWastes = 551;
	case CoastOfPeace = 556;
	case Mort = 560;
	case NewlandDesert = 565;
	case NewlandCity = 566;
	case Newland = 567;
	case PerpetualWastelands = 570;
	case Aegean = 585;
	case WartornValley = 586;
	case CentralArteryValley = 590;
	case DeepArteryValley = 595;
	case VarmintWoods = 600;
	case BelialForest = 605;
	case SouthernArteryValley = 610;
	case SouthernFoulsHills = 615;
	case EasternFoulsPlain = 620;
	case MilkyWay = 625;
	case PleasantMeadows = 630;
	case StretEastBank = 635;
	case Tir = 640;
	case TirCounty = 646;
	case GreaterTirCounty = 647;
	case UpperStretEastBank = 650;
	case Andromeda = 655;
	case CoastOfTranquility = 656;
	case BrokenShores = 665;
	case Clondyke = 670;
	case GalwayCounty = 685;
	case GalwayShire = 687;
	case LushFields = 695;
	case MutantDomain = 696;
	case OmniHQ = 700;
	case OmniEnt = 705;
	case OmniTrade = 710;
	case OmniForest = 716;
	case GreaterOmniForest = 717;
	case RomeRed = 730;
	case RomeBlue = 735;
	case RomeGreen = 740;
	case TheReck = 750;
	case FourHoles = 760;
	case StretWestBank = 790;
	case HolesInTheWall = 791;
	case TheLongestRoad = 795;
	case Borealis = 800;
	case HoloworldOmniTraining = 950;
	case ParkClanTraining = 952;
	case JunkyardNeutralTraining = 954;
	case JobeResearch = 4_001;
	case BurningMarshes = 4_005;
	case FixerGrid = 4_107;
	case NascenseFrontier = 4_310;
	case NascenseWilds = 4_311;
	case NascenseSwamp = 4_312;
	case PenumbraForest = 4_320;
	case PenumbraValley = 4_321;
	case PenumbraHollow = 4_322;
	case PandemoniumCaina = 4_328;
	case PandemoniumAntenora = 4_329;
	case PandemoniumPtolemea = 4_330;
	case PandemoniumJudecca = 4_331;
	case UnicornOutpost = 4_364;
	case Sector13 = 4_365;
	case Sector28 = 4_366;
	case Sector35 = 4_367;
	case APFHub = 4_389;
	case JobePlatform = 4_530;
	case JobeHarbor = 4_531;
	case JobeMarket = 4_532;
	case JobePlaza = 4_533;
	case ElysiumSouth = 4_540;
	case ElysiumWest = 4_541;
	case Elysium = 4_542;
	case ElysiumEast = 4_543;
	case ElysiumNorth = 4_544;
	case ICCShuttleport = 4_582;
	case Inferno = 4_605;
	case AbanGarden = 4_676;
	case ThrakGarden = 4_677;
	case EnelGarden = 4_678;
	case EnelsSanctuary = 4_679;
	case ShereGarden = 4_680;
	case SheresSanctuary = 4_681;
	case OcraGarden = 4_682;
	case RochGarden = 4_683;
	case GiltharGarden = 4_684;
	case GiltharsSanctuary = 4_685;
	case DaljaGarden = 4_686;
	case DaljasSanctuary = 4_687;
	case CamaGarden = 4_688;
	case CamasSanctuary = 4_689;
	case VanyaGarden = 4_690;
	case VanyasSanctuary = 4_691;
	case GalahadGarden = 4_692;
	case GalahadsSanctuary = 4_693;
	case MordethGarden = 4_694;
	case MordethsSanctuary = 4_695;
	case DantesSanctuary = 4_696;
	case MacciavellisSanctuary = 4_697;
	case OcrasSanctuary = 4_698;
	case RochsSanctuary = 4_699;
	case AdonisCity = 4_872;
	case AdonisAbyss = 4_873;
	case ScheolUpper = 4_880;
	case ScheolLower = 4_881;
	case UnicornDefenceHub = 6_007;
	case LoxHub = 6_013;
	case ThreeCratersWest = 6_101;
	case ThreeCratersEast = 6_102;
	case MinesLvl30 = 6_300;
	case MinesLvl60 = 6_301;
	case MinesLvl100 = 6_302;
	case MinesLvl150 = 6_303;
	case MinesLvl200 = 6_304;
	case MinesLvl214 = 6_305;
	case MinesLvl220 = 6_306;
	case UturnCanyon = 6_550;
	case UturnForest = 6_551;
	case Arete = 6_553;
}
