DROP TABLE IF EXISTS playfields;
CREATE TABLE playfields (
	`id` INT(11) PRIMARY KEY NOT NULL,
	`long_name` VARCHAR(250) NOT NULL UNIQUE,
	`short_name` VARCHAR(30) UNIQUE
);
INSERT INTO playfields (id, long_name, short_name) VALUES
(760, '4 Holes', '4HO'),
(655, 'Andromeda', 'AND'),
(585, 'Aegean', 'AEG'),
(540, 'Old Athen', 'OA'),
(550, 'Athen Shire', 'AS'),
(545, 'West Athens', 'WA'),
(505, 'Avalon', 'AV'),
(605, 'Belial Forest', 'BF'),
(800, 'Borealis', 'BOR'),
(665, 'Broken Shores', 'BS'),
(590, 'Central Artery Valley', 'CAV'),
(670, 'Clondyke', 'CLON'),
(556, 'Coast of Peace', 'CP'),
(656, 'Coast of Tranquility', 'CT'),
(595, 'Deep Artery Valley', 'DAV'),
(620, 'Eastern Fouls Plain', 'EFP'),
(685, 'Galway County', 'GC'),
(687, 'Galway Shire', 'GS'),
(717, 'Greater Omni Forest', 'GOF'),
(647, 'Greater Tir County', 'GTC'),
(791, 'Holes in the Wall', 'HITW'),
(695, 'Lush Fields', 'LF'),
(625, 'Milky Way', 'MW'),
(560, 'Mort', 'MORT'),
(696, 'Mutant Domain', 'MD'),
(567, 'Newland', 'NL'),
(566, 'Newland City', 'NC'),
(565, 'Newland Desert', 'NLD'),
(716, 'Omni Forest', 'OF'),
(705, 'Omni-1 Entertainment', 'ENT'),
(700, 'Omni-1 HQ', 'OHQ'),
(710, 'Omni-1 Trade', 'OT'),
(570, 'Perpetual Wastelands', 'PW'),
(630, 'Pleasant Meadows', 'PM'),
(735, 'Rome Blue', 'RB'),
(740, 'Rome Green', 'RG'),
(730, 'Rome Red', 'RR'),
(610, 'Southern Artery Valley', 'SAV'),
(615, 'Southern Fouls Hills', 'SFH'),
(635, 'Stret East Bank', 'SEB'),
(790, 'Stret West Bank', 'SWB'),
(795, 'The Longest Road', 'TLR'),
(640, 'Tir', 'TIR'),
(646, 'Tir County', 'TC'),
(650, 'Upper Stret East Bank', 'USEB'),
(600, 'Varmint Woods', 'VW'),
(551, 'Wailing Wastes', 'WW'),
(586, 'Wartorn Valley', 'WV'),
(6550, 'Uturn Canyon', 'UC'),
(6551, 'Uturn Forest', 'UF'), 
(6102, 'Three Craters East', '3CE'),
(6101, 'Three Craters West', '3CW'),
(6553, 'Arete', 'ARETE'),



(4872, 'Adonis City', 'ADOCITY'),
(4873, 'Adonis Abyss', 'ADO'),
(4542, 'Elysium', 'ELY'),
(4543, 'Elysium East', 'ELYEAST'),
(4544, 'Elysium North', 'ELYNORTH'),
(4540, 'Elysium South', 'ELYSOUTH'),
(4541, 'Elysium West', 'ELYWEST'),
(4605, 'Inferno', 'INF'),
(4005, 'Inferno Burning Marshes', 'INFMARSHES'),
(4531, 'Jobe Harbor', 'HARBOR'),
(4532, 'Jobe Market', 'MARKET'),
(4530, 'Jobe Platform', 'PLATFORM'),
(4533, 'Jobe Plaza', 'PLAZA'),
(4001, 'Jobe Research', 'RESEARCH'),
(4310, 'Nascense Frontier', 'NASCFRONTIER'),
(4312, 'Nascense Swamp', 'NASCSWAMP'),
(4311, 'Nascense Wilds', 'NASCWILDS'),
(4320, 'Penumbra Forest', 'PENFOREST'),
(4322, 'Penumbra Hollow', 'PENHOLLOW'),
(4321, 'Penumbra Valley', 'PENVALLEY'),
(4329, 'Pandemonium Antenora', 'PANDEANTENORA'),
(4328, 'Pandemonium Caina', 'PANDECAINA'),
(4331, 'Pandemonium Judecca', 'PANDEJUDECCA'),
(4330, 'Pandemonium Ptolemea', 'PANDEPTOLEMEA'),
(4880, 'Scheol Upper', 'SCHEOLUPPER'),
(4881, 'Scheol Lower', 'SCHEOLLOWER');
