DROP TABLE IF EXISTS `ingredient`;
CREATE TABLE `ingredient` (
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`aoid` INT,
	`where` TEXT
);

INSERT INTO `ingredient`(`name`, `aoid`, `where`) VALUES
('Balance Adjuster - Left', 150910, 'sold by Arul Saba'),
('Balance Adjuster - Right', 150911, 'sold by Arul Saba'),
('Small Silver Ingot', 150914, 'Rubi-Ka loot'),
('Personal Furnace', 150930, 'sold by Arul Saba and tradeskill terminals'),
('Personal Furnace', 150930, 'sold by Arul Saba and tradeskill terminals'),
('Robot Junk', 42620, 'drops from robotic mobs on Rubi-Ka'),
('Nano Circuitry Wire', 150918, 'sold by Arul Saba'),
('Wire Drawing Machine', 150916, 'tradeskill terminals'),
('Screwdriver', 150922, 'tradeskill terminals'),

('Unbalanced Bracelet Blueprints',150867,'sold by Arul Saba'),
('Unbalanced Bracelet Blueprints',150869,'sold by Arul Saba'),
('Unbalanced Bracelet Blueprints',150870,'sold by Arul Saba'),
('Unbalanced Bracelet Blueprints',150871,'sold by Arul Saba'),

('Arbiter Gem of the Frail Juggernaut', 229980, 'Nascence static dungeons'),
('Arbiter Gem of the Broken Moebius', 230041, 'Nascence static dungeons'),
('Arbiter Gem of the Novice Brawler', 230047, 'Nascence static dungeons'),
('Arbiter Gem of Fiery Plasma', 230088, 'Nascence static dungeons'),
('Arbiter Gem of the Empty Desert', 230132, 'Nascence static dungeons'),
('Arbiter Gem of the Icy Tundra', 230172, 'Nascence static dungeons'),
('Arbiter Gem of the Craggy Landscape', 230212, 'Nascence static dungeons'),
('Arbiter Gem of the Scarlet Sky', 230252, 'Nascence static dungeons'),
('Arbiter Gem of Decayed Glory', 230292, 'Nascence static dungeons'),
('Arbiter Gem of the Insidious Killer', 230332, 'Nascence static dungeons'),

('Arbiter Gem of the Eternal Juggernaut', 165385, 'Scheol static dungeons'),
('Arbiter Gem of the Infinite Moebius', 168428, 'Scheol static dungeons'),
('Arbiter Gem of the Bruised Brawler', 168469, 'Scheol static dungeons'),
('Arbiter Gem of Burning Plasma', 168509, 'Scheol static dungeons'),
('Arbiter Gem of the Searing Desert', 168549, 'Scheol static dungeons'),
('Arbiter Gem of the Frozen Tundra', 168616, 'Scheol static dungeons'),
('Arbiter Gem of the Jagged Landscape', 168713, 'Scheol static dungeons'),
('Arbiter Gem of the Rainbow-hued Sky', 168753, 'Scheol static dungeons'),
('Arbiter Gem of Corroded Glory', 168793, 'Scheol static dungeons'),
('Arbiter Gem of the Silent Killer', 168839, 'Scheol static dungeons'),

('Monarch Gem of the Eternal Juggernaut',165386,'Adonis static dungeons'),
('Monarch Gem of the Infinite Moebius',168429,'Adonis static dungeons'),
('Monarch Gem of the Bruised Brawler',168470,'Adonis static dungeons'),
('Monarch Gem of Burning Plasma',168510,'Adonis static dungeons'),
('Monarch Gem of the Searing Desert',168550,'Adonis static dungeons'),
('Monarch Gem of the Frozen Tundra',168617,'Adonis static dungeons'),
('Monarch Gem of the Jagged Landscape',168714,'Adonis static dungeons'),
('Monarch Gem of the Rainbow-hued Sky',168754,'Adonis static dungeons'),
('Monarch Gem of Corroded Glory',168794,'Adonis static dungeons'),
('Monarch Gem of the Silent Killer',168840,'Adonis static dungeons'),

('Emperor Gem of the Eternal Juggernaut',165387,'Penumbra static dungeons'),
('Emperor Gem of the Infinite Moebius',168430,'Penumbra static dungeons'),
('Emperor Gem of the Bruised Brawler',168471,'Penumbra static dungeons'),
('Emperor Gem of Burning Plasma',168511,'Penumbra static dungeons'),
('Emperor Gem of the Searing Desert',168551,'Penumbra static dungeons'),
('Emperor Gem of the Frozen Tundra',168618,'Penumbra static dungeons'),
('Emperor Gem of the Jagged Landscape',168715,'Penumbra static dungeons'),
('Emperor Gem of the Rainbow-hued Sky',168755,'Penumbra static dungeons'),
('Emperor Gem of Corroded Glory',168795,'Penumbra static dungeons'),
('Emperor Gem of the Silent Killer',168841,'Penumbra static dungeons'),

('Stellar Jewel of the Eternal Juggernaut',165388,'Inferno static dungeons'),
('Stellar Jewel of the Infinite Moebius',168431,'Inferno static dungeons'),
('Stellar Jewel of the Bruised Brawler',168472,'Inferno static dungeons'),
('Stellar Jewel of Burning Plasma',168512,'Inferno static dungeons'),
('Stellar Jewel of the Searing Desert',168552,'Inferno static dungeons'),
('Stellar Jewel of the Frozen Tundra',168619,'Inferno static dungeons'),
('Stellar Jewel of the Jagged Landscape',168716,'Inferno static dungeons'),
('Stellar Jewel of the Rainbow-hued Sky',168756,'Inferno static dungeons'),
('Stellar Jewel of Corroded Glory',168796,'Inferno static dungeons'),
('Stellar Jewel of the Silent Killer',168842,'Inferno static dungeons'),

('Galactic Jewel of the Eternal Juggernaut',165389,'Alappaa'),
('Galactic Jewel of the Infinite Moebius',168432,'Alappaa'),
('Galactic Jewel of the Bruised Brawler',168473,'Alappaa'),
('Galactic Jewel of Burning Plasma',168513,'Alappaa'),
('Galactic Jewel of the Searing Desert',168553,'Alappaa'),
('Galactic Jewel of the Frozen Tundra',168620,'Alappaa'),
('Galactic Jewel of the Jagged Landscape',168717,'Alappaa'),
('Galactic Jewel the Rainbow-hued Sky',168757,'Alappaa'),
('Galactic Jewel of Corroded Glory',168797,'Alappaa'),
('Galactic Jewel of the Silent Killer',168843,'Alappaa');

CREATE INDEX IF NOT EXISTS `ingredient_aoid_idx` ON `ingredient`(`aoid`);