DROP TABLE IF EXISTS boss_lootdb;
CREATE TABLE boss_lootdb (
	`bossid` INT NOT NULL,
	`itemname` VARCHAR(100) NOT NULL
);
INSERT INTO `boss_lootdb` VALUES
(1,'Massive Bolt Charger'),
(2,'Armplates of Meteorite Assembly'),
(2,'Boots of Stolen Comet Speed'),
(2,'Gauntlets of Star Confabulation'),
(2,'Moon Watcher Helmet'),
(2,'Overcoat of the Firmament'),
(2,'Shoulderpads of Asteroid Calling'),
(2,'Vest of Torpid Sunrays'),
(3,'Brother''s Brass Knuckles'),
(3,'Crawler Armor Boots'),
(3,'Crawler Armor Gloves'),
(3,'Crawler Armor Hood'),
(3,'Crawler Armor Pants'),
(3,'Crawler Armor Shoulder Pad'),
(3,'Crawler Armor Sleeves'),
(3,'Crawler Body Armor'),
(4,'Subspace Mesh'),
(4,'Meta-Cerebellum Ring'),
(5,'Meta-Cerebellum Ring'),
(6,'Two-Dimensional Hole'),
(6,'Maiden''s Gloves'),
(7,'Short Circuited Spiritech Circlet'),
(7,'Short Circuited Spiritech Circlet'),
(8,'Piercing Evil'),
(9,'Bellum Badonis Armor Boots'),
(9,'Bellum Badonis Armor Gloves'),
(9,'Bellum Badonis Armor Helmet'),
(9,'Bellum Badonis Armor Sleeves'),
(9,'Bellum Badonis Body Armor'),
(9,'Bellum Badonis Coat'),
(9,'Bellum Badonis Shoulderpads'),
(9,'Finely Refined Notum'),
(9,'Master''s Eye'),
(9,'Lava capsule'),
(10,'Aquarius'' Boots of Small Steps'),
(10,'Aquarius''s Multitask Calculator'),
(10,'Intuitive Memory of the Aquarius'),
(10,'Mediative Gloves of the Aquarius'),
(11,'Aries'' Tiara of the Quick Witted'),
(11,'Boon of Aries'),
(11,'Dynamic Sleeve of Aries'),
(11,'Quick-Draw Holster of Aries'),
(12,'Elysian Protector''s Cuirass'),
(12,'Focus-Funneling Spirit'),
(13,'Blood-Soaked Cloak of Dishonour'),
(14,'Armplates of Meteorite Assembly'),
(14,'Boots of Stolen Comet Speed'),
(14,'Gauntlets of Star Confabulation'),
(14,'Moon Watcher Helmet'),
(14,'Shoulderpads of Asteroid Calling'),
(14,'Vest of Torpid Sunrays'),
(14,'Pernicious Body Armor'),
(14,'Overcoat of the Firmament'),
(15,'Spirit Ring of Self-Education'),
(15,'Spirit Training Program'),
(16,'Bracer of Recondite Flames'),
(16,'Human Skin Hood'),
(17,'Eremite Macro Sensor'),
(17,'Eremite Macro Sensor'),
(17,'Eremite Psychic Sensor'),
(18,'Bigot''s Armband of Sacrifice'),
(18,'Bigot''s Bracer of Sacrifice'),
(18,'Bigot''s Earring of Sacrifice'),
(18,'Bigot''s Necklace of Sacrifice'),
(18,'Bigot''s Ring of Sacrifice'),
(19,'Finely Refined Notum'),
(19,'Hood of Black Waters'),
(20,'Finely Refined Notum'),
(21,'Elysian Protector''s Cuirass'),
(21,'Focus-Funneling Spirit'),
(22,'Cancer''s Gloves of Automatic Knowledge'),
(22,'Cancer''s Ring of Circumspection'),
(22,'Cancer''s Silver Boots of the Autodidact'),
(22,'Cancer''s Time-Saving Memory'),
(23,'Cantankerous''s Headwear'),
(23,'Spirit Tech Apparatus: Double Barrel'),
(23,'Spirit Tech Apparatus: Long Muzzle'),
(23,'Spirit Tech Apparatus: Short Muzzle'),
(23,'Fingerspitzgefuhl'),
(24,'Capricorn Bracer of Toxication'),
(24,'Capricorn''s Guide to Alchemy'),
(24,'Capricorn''s Reliable Memory'),
(24,'Gloves of the Caring Capricorn'),
(25,'Shuffling Finger'),
(26,'Blackbird'),
(26,'Blackbird'),
(26,'Chiroptera'),
(26,'Chiroptera'),
(26,'Howlet'),
(26,'Howlet'),
(27,'Focus-Funneling Device'),
(27,'Gamboling Master''s Wear'),
(27,'Jagged Claw'),
(27,'Shapeshifter''s Vest'),
(27,'Spirit Tech Circlet of Cerubin'),
(27,'Grasping Ring'),
(27,'Neck Eye'),
(28,'Monitor Smoking Suit'),
(29,'Shroud of Darkest Night'),
(30,'Modified A-4000 NCU-sheet'),
(30,'Modified A-4000 Sensory Panel'),
(31,'Modified A-4000 NCU-sheet'),
(31,'Modified A-4000 Sensory Panel'),
(32,'Eremite Macro Sensor'),
(32,'Eremite Micro Sensor'),
(32,'Eremite Psychic Sensor'),
(33,'Kaehler Uniform Sleeves'),
(33,'Mendix Biomech AR-2'),
(34,'Problem Avoiding Device'),
(34,'Problem Seeking Device'),
(34,'Problem Solving Device'),
(35,'Frederickson Cumulus model'),
(35,'Frederickson Micro-kinetic Sleeves'),
(35,'Frederickson''s Kinetic Sleeves'),
(36,'Syndicate Messenger Gun'),
(37,'Lindgren Spirit'),
(38,'Spirit Tech Apparatus: Double Barrel'),
(38,'Spirit Tech Apparatus: Long Muzzle'),
(38,'Spirit Tech Apparatus: Short Muzzle'),
(38,'Doubleknit Pants'),
(38,'The Cause of Headache'),
(39,'Commander''s Ceremonial Chest Plate'),
(39,'Cranky Golem Eye'),
(39,'Spirit Tech Apparatus: Double Barrel'),
(39,'Spirit Tech Apparatus: Long Muzzle'),
(39,'Spirit Tech Apparatus: Short Muzzle'),
(40,'Slippers of Screaming'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Grail of the White Feather'),
(41,'Conflagrant Syndicate Messenger Gun'),
(41,'Grail of the Antlered King'),
(41,'Head Symbiant of the Love Child'),
(42,'Candy Cord'),
(43,'Kevlar Armbands'),
(43,'The Third Eye of Daria'),
(43,'Very Very Very Cool Top'),
(43,'Very Very Very Hot Pants'),
(44,'Finely Refined Notum'),
(45,'Finely Refined Notum'),
(46,'Spirit of the Innocent'),
(47,'Fanatic''s Jacket'),
(48,'Diamond-Matrix Mesh'),
(48,'Kick Pistol'),
(48,'Titan Viper Tattoo'),
(49,'Diamond-Matrix Mesh'),
(49,'Kick Pistol'),
(50,'Counterfeit Omni Epaulet'),
(51,'Elysian Protector''s Cuirass'),
(51,'Focus-Funneling Spirit'),
(52,'Blackshirt of Zuwadza'),
(52,'Cheeping Flamethrower of Zuwadza'),
(52,'Stinging Snake Tattoo'),
(53,'Enkindled Spirit Focus'),
(54,'Gift of the Old Gargantula'),
(55,'Fanatic''s Jacket'),
(56,'Finely Refined Notum'),
(57,'Beeping Backpack'),
(57,'Junior Master of Combustion'),
(58,'Fleshchopper'),
(58,'Notum Focus'),
(58,'Spirit Focus'),
(58,'Toothpicker'),
(59,'Collector Pants of Gemini'),
(59,'Cross Dimensional Gyro of Gemini'),
(59,'Gemini''s Double Band of Linked Information'),
(59,'Gemini''s Green Scope of Variety'),
(60,'Longshot'),
(60,'Superior Sentinel Armor Boots'),
(60,'Superior Sentinel Armor Gloves'),
(60,'Superior Sentinel Armor Pants'),
(60,'Superior Sentinel Armor Sleeves'),
(60,'Superior Sentinel Body Armor'),
(61,'Dust Collector'),
(61,'Dustbrigade Commander Boots'),
(61,'Dustbrigade Commander Chestpiece'),
(61,'Dustbrigade Commander Gloves'),
(61,'Dustbrigade Commander Skirt'),
(61,'Dustbrigade Commander Sleeves'),
(61,'Dustbrigade Trooper Boots'),
(61,'Dustbrigade Trooper Chestpiece'),
(61,'Dustbrigade Trooper Gloves'),
(61,'Dustbrigade Trooper Pants'),
(61,'Dustbrigade Trooper Sleeves'),
(61,'Mother Nitrogena'),
(61,'Explorer Boots'),
(61,'Pants of Participation'),
(61,'Safeguarded NCU Memory Unit'),
(61,'Specialized Dustbrigade Vambrace - Atrox Breed'),
(61,'Specialized Dustbrigade Vambrace - Nano Breed'),
(61,'Specialized Dustbrigade Vambrace - Opifex Breed'),
(61,'Threatening Trousers'),
(62,'Dust Collector'),
(62,'Dustbrigade Commander Boots'),
(62,'Dustbrigade Commander Chestpiece'),
(62,'Dustbrigade Commander Gloves'),
(62,'Dustbrigade Commander Skirt'),
(62,'Dustbrigade Commander Sleeves'),
(62,'Dustbrigade Trooper Boots'),
(62,'Dustbrigade Trooper Chestpiece'),
(62,'Dustbrigade Trooper Gloves'),
(62,'Dustbrigade Trooper Pants'),
(62,'Dustbrigade Trooper Sleeves'),
(62,'Mother Nitrogena'),
(62,'Explorer Boots'),
(62,'Pants of Participation'),
(62,'Specialized Dustbrigade Vambrace - Nano Breed'),
(62,'Specialized Dustbrigade Vambrace - Opifex Breed'),
(62,'Threatening Trousers'),
(63,'Dust Collector'),
(63,'Dustbrigade Commander Boots'),
(63,'Dustbrigade Commander Chestpiece'),
(63,'Dustbrigade Commander Gloves'),
(63,'Dustbrigade Commander Skirt'),
(63,'Dustbrigade Commander Sleeves'),
(63,'Dustbrigade Trooper Boots'),
(63,'Dustbrigade Trooper Chestpiece'),
(63,'Dustbrigade Trooper Gloves'),
(63,'Dustbrigade Trooper Pants'),
(63,'Dustbrigade Trooper Sleeves'),
(63,'Mother Nitrogena'),
(63,'Explorer Boots'),
(63,'Pants of Participation'),
(62,'Safeguarded NCU Memory Unit'),
(62,'Specialized Dustbrigade Vambrace - Atrox Breed'),
(63,'Safeguarded NCU Memory Unit'),
(63,'Specialized Dustbrigade Vambrace - Opifex Breed'),
(63,'Specialized Dustbrigade Vambrace - Atrox Breed'),
(63,'Specialized Dustbrigade Vambrace - Nano Breed'),
(63,'Threatening Trousers'),
(64,'Standard Medical Epaulet'),
(65,'Armplates of Meteorite Assembly'),
(65,'Boots of Stolen Comet Speed'),
(65,'Gauntlets of Star Confabulation'),
(65,'Moon Watcher Helmet'),
(65,'Overcoat of the Firmament'),
(65,'Shoulderpads of Asteroid Calling'),
(65,'Vest of Torpid Sunrays'),
(66,'Longshot'),
(66,'Omni-Armed Forces Armor'),
(66,'Omni-Armed Forces Boots'),
(66,'Omni-Armed Forces Gloves'),
(66,'Omni-Armed Forces Pants'),
(66,'Omni-Armed Forces Sleeves'),
(67,'Shuffling Finger'),
(68,'Predator Armband'),
(68,'Predator Armor Boots'),
(68,'Predator Armor Facemask'),
(68,'Predator Armor Gloves'),
(68,'Predator Armor Pants'),
(68,'Predator Armor Vest'),
(68,'Predator''s Circlet'),
(69,'Average Gloves'),
(69,'Blood-Stained Bat'),
(69,'Blood-Stained Mace'),
(69,'Boots of Azure Reveries'),
(69,'Breastplate of Azure Reveries'),
(69,'Flaxen Notum Pants'),
(69,'Gloves of Azure Reveries'),
(69,'Helmet of Azure Reveries'),
(69,'Pants of Azure Reveries'),
(69,'Pioneer of Jobe Cloak'),
(69,'Rust-pitted Ring'),
(69,'Sleeves of Azure Reveries'),
(69,'Stone Samurai Boots'),
(70,'Compagnero'),
(71,'Golem''s Warm Notum Hood'),
(71,'Spirit Tech Apparatus: Double Barrel'),
(71,'Spirit Tech Apparatus: Long Muzzle'),
(71,'Spirit Tech Apparatus: Short Muzzle'),
(71,'Spirit of Opportunity'),
(72,'Droid Control-device'),
(72,'Modified Aggression Enhancer'),
(73,'Armplates of Meteorite Assembly'),
(73,'Boots of Stolen Comet Speed'),
(73,'Gauntlets of Star Confabulation'),
(73,'Moon Watcher Helmet'),
(73,'Overcoat of the Firmament'),
(73,'Shoulderpads of Asteroid Calling'),
(73,'Vest of Torpid Sunrays'),
(74,'Armplates of Meteorite Assembly'),
(74,'Boots of Stolen Comet Speed'),
(74,'Gauntlets of Star Confabulation'),
(74,'Moon Watcher Helmet'),
(74,'Overcoat of the Firmament'),
(74,'Shoulderpads of Asteroid Calling'),
(74,'Vest of Torpid Sunrays'),
(74,'Mark of the Fisher King'),
(75,'Maul of Gwyddawg'),
(75,'Conflagrant Syndicate Messenger Gun'),
(75,'Maul of Menestyr'),
(76,'White Sack'),
(77,'Finely Refined Notum'),
(77,'Floating Bag of Jukes'),
(78,'Customized IMI Desert Reet 1000'),
(78,'Sealed Order BLCG-7791'),
(78,'Sealed Order FPGA-202'),
(78,'Sealed Order XITL-0127'),
(79,'Enthusiastic Spirit Helper of the Leo'),
(79,'Leo''s Faithful Boots of Ancient Gold'),
(79,'Leo''s Grandiose Gold Armband of Plenty'),
(79,'Leo''s Mellow Gold Pad of Auto-Support'),
(80,'Aim of Libra'),
(80,'Libra''s Charming Assistant'),
(80,'Urbane Pants of Libra'),
(80,'Well Balanced Spirit Helper of Libra'),
(81,'Finely Refined Notum'),
(81,'Pelisse of the Elysian Nymph'),
(82,'Mystical Green Hood'),
(83,'Predator Armband'),
(83,'Predator Armor Boots'),
(83,'Predator Armor Facemask'),
(83,'Predator Armor Gloves'),
(83,'Predator Armor Pants'),
(83,'Predator Armor Vest'),
(83,'Predator''s Circlet'),
(84,'Eleet Doll'),
(84,'Eye of the Hunter'),
(84,'Ljotur Beets of Clamping'),
(84,'Ljotur Pants of Cornucopia'),
(84,'Mirror Mask of Ljotur'),
(84,'NanoCrystal (Candycane)'),
(84,'Twelve-Fingered Graspers of Ljotur'),
(84,'Unbecoming Sleeves of Ljotur'),
(84,'Upper Part of Ljotur'),
(85,'Bloodlust'),
(85,'Eye of the Evening Star'),
(85,'Pensive Spirit Phulakterion'),
(85,'Ring of Computing'),
(85,'Ring of Divine Teardrops'),
(85,'Silver Spider Knuckledusters'),
(85,'Spear of Forbidden Ceremonies'),
(85,'Stock of Bacam-Xum'),
(85,'Watchful Spirit Phulakterion'),
(86,'Problem Avoiding Device'),
(86,'Problem Seeking Device'),
(86,'Problem Solving Device'),
(87,'Jobe City Guard Personal Pistol'),
(87,'Jobe Surveyor Personal Pistol'),
(87,'Jobe City Guard Personal Pistol'),
(87,'Jobe Surveyor Personal Pistol'),
(88,'Mantis Egg'),
(88,'Queen Blade'),
(88,'Mantis Scissors'),
(89,'Poetic Pants'),
(89,'Poetic Sleeves'),
(89,'Poetic Stretch-band'),
(90,'Armplates of Meteorite Assembly'),
(90,'Boots of Stolen Comet Speed'),
(90,'Gauntlets of Star Confabulation'),
(90,'Moon Watcher Helmet'),
(90,'Overcoat of the Firmament'),
(90,'Shoulderpads of Asteroid Calling'),
(90,'Vest of Torpid Sunrays'),
(91,'Energized Carbonan Oven Mittens'),
(91,'Shades of Lucubration'),
(92,'Chief Cook Cleaver'),
(92,'Chief Cook Cleaver'),
(92,'Ring that Turns Rocks'),
(92,'Longsword of the Illuminated'),
(92,'Sword of the Illuminated'),
(93,'Gutting Hook'),
(93,'Torturing Tool'),
(94,'Whistle-box'),
(95,'Finely Refined Notum'),
(96,'Fractured Sanity'),
(96,'Neleb''s Nano-circuit Robe'),
(96,'Neleb''s Notum Battlerod'),
(96,'Fractured Sanity'),
(96,'Cortex of the Executioner'),
(96,'Brainchopper'),
(96,'Galahad Inc. Cinnamon Scout'),
(97,'Anything'),
(97,'Boots of Azure Reveries'),
(97,'Breastplate of Azure Reveries'),
(97,'Gloves of Azure Reveries'),
(97,'Helmet of Azure Reveries'),
(97,'Nelly Johnsons Little Black Dress'),
(97,'Pants of Azure Reveries'),
(97,'Sleeves of Azure Reveries'),
(98,'Nophex Plasma Destroyer I'),
(98,'Notum Infused Kevlar Armor Boots'),
(98,'Notum Infused Kevlar Armor Gloves'),
(98,'Notum Infused Kevlar Armor Pants'),
(98,'Notum Infused Kevlar Armor Sleeves'),
(98,'Notum Infused Kevlar Body Armor'),
(98,'Pulsing Notum Disruptor'),
(99,'Erratic Notum Disruptor'),
(100,'Fluctuating Anti-Matter Generator'),
(101,'Anti-Gravity Unit'),
(101,'Flower Guard Gofleprod'),
(101,'Flower Guard Triplate Metal Armor Cloak'),
(101,'Flower Guard Triplate Metal Boots'),
(101,'Flower Guard Triplate Metal Gauntlets'),
(101,'Flower Guard Triplate Metal Helmet'),
(101,'Rusted Juggernaut Rear Mitrailleuse'),
(101,'Standard Juggernaut Nano Containment Module'),
(102,'Metallic Hoop'),
(103,'Spirit Ring of Self-Education'),
(103,'Spirit Training Program'),
(104,'Capsule of Thin Blood'),
(105,'Predator Armband'),
(105,'Predator Armor Boots'),
(105,'Predator Armor Facemask'),
(105,'Predator Armor Gloves'),
(105,'Predator Armor Pants'),
(105,'Predator Armor Vest'),
(105,'Predator''s Circlet'),
(106,'Boots of Azure Reveries'),
(106,'Pain of Patricia'),
(106,'Breastplate of Azure Reveries'),
(106,'Gloves of Azure Reveries'),
(106,'Helmet of Azure Reveries'),
(106,'Luxurious Rubber Pants'),
(106,'Luxurious Rubber Shirt'),
(106,'Luxurious Rubber Sleeves'),
(106,'Un-repairable Pain of Patricia'),
(106,'Pants of Azure Reveries'),
(106,'Reign of Patricia'),
(106,'Sleeves of Azure Reveries'),
(107,'Blackpack'),
(107,'Doctor''s Pill Pack'),
(107,'Syndicate Shades'),
(108,'Blackpack'),
(108,'Doctor''s Pill Pack'),
(108,'Syndicate Shades'),
(109,'Boots of Azure Reveries'),
(109,'Breastplate of Azure Reveries'),
(109,'Gloves of Azure Reveries'),
(109,'Heavy Notum Tank Armor'),
(109,'Helmet of Azure Reveries'),
(109,'Light Notum Tank Armor'),
(109,'Medium Notum Tank Armor'),
(109,'Pants of Azure Reveries'),
(109,'Sleeves of Azure Reveries'),
(110,'Phatmos'' Booty'),
(110,'Phatmos'' Loot'),
(111,'Cosmic Guide of the Pisces'),
(111,'Mystery of Pisces'),
(111,'Octopus Contraption of the Pisces'),
(111,'Octopus Contraption of the Pisces'),
(112,'Hood of Wicked Inspiration'),
(112,'Pit Demon Heart'),
(112,'Pit Demon Spit'),
(113,'Support Wire'),
(114,'Nano Crystal (Team Beacon Warp)'),
(114,'NanoCrystal (Nullity Sphere MK II)'),
(115,'Starched Armbands'),
(116,'Journeyman Durable Boost'),
(116,'The Expensive Kevlar Vest of Professor Jones'),
(117,'Bellum Badonis Armor Boots'),
(117,'Bellum Badonis Armor Gloves'),
(117,'Bellum Badonis Armor Helmet'),
(117,'Bellum Badonis Armor Sleeves'),
(117,'Bellum Badonis Body Armor'),
(117,'Bellum Badonis Coat'),
(117,'Bellum Badonis Shoulderpads'),
(118,'Sword of Curiosity'),
(118,'Sword of Wonder'),
(119,'Disposal Unit Electrical Toolset'),
(119,'Rat Catcher Goggles'),
(120,'Boots of Azure Reveries'),
(120,'Breastplate of Azure Reveries'),
(120,'Fancy Stethoscopic Glasses'),
(120,'Gloves of Azure Reveries'),
(120,'Helmet of Azure Reveries'),
(120,'Pants of Azure Reveries'),
(120,'Sleeves of Azure Reveries'),
(121,'Sword of Curiosity'),
(121,'Sword of Wonder'),
(121,'Suzerain''s Political Chief Headwear'),
(122,'Spirit Training Program'),
(123,'Comfort of the Sagittarius'),
(123,'First Creation of the Sagittarius'),
(123,'Sagittarius''s Hearty Spirit Helper'),
(123,'Strong Mittens of the Sagittarius'),
(124,'Boots of Stolen Comet Speed'),
(124,'Gauntlets of Star Confabulation'),
(124,'Moon Watcher Helmet'),
(124,'Overcoat of the Firmament'),
(124,'Shoulderpads of Asteroid Calling'),
(124,'Vest of Torpid Sunrays'),
(124,'Armplates of Meteorite Assembly'),
(125,'Short Circuited Spiritech Circlet'),
(126,'Punters of the Scorpio'),
(126,'Sash of Scorpio Strength'),
(126,'Scorpio''s Aim of Anger'),
(126,'Scorpio''s Shell of Change'),
(127,'Taurus'' Spirit of Patience'),
(127,'JAME Blaster Prototype XII'),
(127,'JAME Blaster Prototype IV'),
(127,'Heavy Bracer'),
(128,'Elysian Protector''s Cuirass'),
(128,'Focus-Funneling Spirit'),
(129,'Bellum Badonis Armor Boots'),
(129,'Bellum Badonis Armor Gloves'),
(129,'Bellum Badonis Armor Helmet'),
(129,'Bellum Badonis Armor Sleeves'),
(129,'Bellum Badonis Body Armor'),
(129,'Bellum Badonis Coat'),
(129,'Bellum Badonis Shoulderpads'),
(130,'Headband of Haste'),
(130,'JAME Blaster Prototype IV'),
(130,'JAME Blaster Prototype XII'),
(131,'Crackerjack Sleeves'),
(131,'Ring of Herodotus'),
(131,'Headband of Haste'),
(132,'Finely Refined Notum'),
(132,'Superior Skylight Shield'),
(133,'Repair Coordination Assistant'),
(134,'Solid Spiritech Mesh'),
(134,'JAME Blaster Prototype IV'),
(134,'JAME Blaster Prototype XII'),
(135,'Chain of Concealment'),
(135,'NanoCrystal (Resonance Blast)'),
(135,'The HSR Detective'),
(136,'Scimitar of Spetses'),
(136,'Sparkling Scimitar of Spetses'),
(137,'Cure for Baldness'),
(138,'Finely Refined Notum'),
(139,'Penumbra Tuaq'),
(140,'Blue Baby Bronto Boots'),
(141,'Superior Sentinel Armor Boots'),
(141,'Superior Sentinel Armor Gloves'),
(141,'Superior Sentinel Armor Helmet'),
(141,'Superior Sentinel Armor Pants'),
(141,'Superior Sentinel Armor Sleeves'),
(141,'Superior Sentinel Body Armor'),
(142,'Omni-Armed Forces Armor'),
(142,'Omni-Armed Forces Boots'),
(142,'Omni-Armed Forces Gloves'),
(142,'Omni-Armed Forces Helmet'),
(142,'Omni-Armed Forces Pants'),
(142,'Omni-Armed Forces Sleeves'),
(143,'Eremite Macro Sensor'),
(143,'Eremite Micro Sensor'),
(143,'Eremite Psychic Sensor'),
(144,'HUD Upgrade: Enhanced Target Acquisition'),
(144,'HUD Upgrade: Personal S.T.M'),
(145,'Aura Magnifier'),
(145,'Cloak of the Wandering Knight'),
(145,'Gaily Painted Hood'),
(145,'Globe of Clarity'),
(145,'Globe of Sufferance'),
(145,'Heavily Padded Overcoat'),
(145,'The Heavy-Headed Staff'),
(145,'Hollow Bone Bracer of Merlin Ambrosius'),
(145,'Chunk of Living Dragon Flesh'),
(145,'Lump of Living Dragon Marrow'),
(145,'Patch of Living Dragon Skin'),
(145,'Piece of Living Dragon Wing'),
(145,'Shard of Living Dragon Skull'),
(145,'Heart of Tarasque'),
(145,'Gall Stone'),
(145,'Robust Backpack'),
(145,'Signet Ring of the Green Knight'),
(145,'Sinew of Tarasque'),
(145,'Smart Hood of the Wanderer'),
(145,'Smelly Butcher Gloves'),
(145,'Edge of the Tarasque'),
(145,'Typical Dragon Tooth Poker'),
(146,'Taurus'' Ring of the Heart'),
(146,'Taurus'' Spirit of Patience'),
(146,'Taurus'' Spirit of Reflection'),
(146,'Taurus'' Swordmaster Spirit'),
(147,'Spirit Ring of Self-Education'),
(147,'Spirit Training Program'),
(148,'Armplates of Elimination'),
(148,'Boots of Concourse'),
(148,'Burden of Competence'),
(148,'Cuirass of Obstinacy'),
(148,'Gauntlets of Deformation'),
(148,'Greaves of Malfeasance'),
(148,'Helmet of Hypocrisy'),
(148,'Shoulderplates of Sabotage'),
(148,'Sigil of Bahomet'),
(148,'Sleeves of Senseless Violence'),
(148,'Star of Ardency'),
(148,'Star of Enterprice'),
(148,'Star of Enticement'),
(148,'Star of Equanimity'),
(148,'Star of Faith'),
(148,'Star of Fidelity'),
(148,'Star of Fortitude'),
(148,'Star of Freedom'),
(148,'Star of Ingenuity'),
(148,'Star of Interchange'),
(148,'Star of Management'),
(148,'Star of Moral'),
(148,'Star of Recovery'),
(148,'Star of Stealth'),
(148,'Sunrise Hilt'),
(148,'Sunset Hilt'),
(148,'Lady of Abandonment'),
(148,'Lady of Hatred'),
(148,'Lady of Deceit'),
(148,'Lady of Pride'),
(148,'Lady of Gluttony'),
(148,'Lady of Anger'),
(148,'Lady of Angst'),
(148,'Lady of Envy'),
(148,'Lady of Greed'),
(148,'Lady of Chaos'),
(148,'Lady of Sloth'),
(148,'Lady of Lust'),
(148,'Lord of Abandonment'),
(148,'Lady of Hatred'),
(148,'Lady of Deceit'),
(148,'Lady of Pride'),
(148,'Lady of Gluttony'),
(148,'Lady of Anger'),
(148,'Lady of Angst'),
(148,'Lady of Envy'),
(148,'Lady of Greed'),
(148,'Lady of Chaos'),
(148,'Lady of Sloth'),
(148,'Lady of Lust'),
(148,'High Lord of Angst'),
(149,'Maar''s Blue Belt of Double Prudence'),
(149,'Maar''s Red Belt of Double Power'),
(149,'Maar''s Yellow Belt of Double Speed'),
(149,'Notum Seed'),
(149,'Novictum Seed'),
(150,'Contained Anti-Matter Generator'),
(150,'NanoCrystal (Shield of the Obedient Servant)'),
(150,'Punishment Rod'),
(150,'Slayerdroid Claw'),
(151,'Breastplate of Spiritual Rites'),
(151,'Breastplate of Technical Ceremonies'),
(151,'Helmet of Spiritual Rites'),
(151,'Helmet of Technical Ceremonies'),
(152,'Left Sleeves of the Pest'),
(152,'NanoCrystal (Corruption of The Pest)'),
(152,'NanoCrystal (Lick of the Pest)'),
(152,'Patch of Pest'),
(152,'Petticoat of Pest'),
(152,'Right Sleeves of the Pest'),
(153,'Ring of Burning Flesh'),
(154,'Joy of the Hunt'),
(154,'Joy of the Race'),
(154,'Killer''s Armor Trousers'),
(154,'Killer''s Armor Sleeve'),
(154,'Sombreous Arm Tattoo''s'),
(155,'Sleeves of Boiling Blood'),
(156,'Neural Interpreting Nball - Melee fighting'),
(157,'Corroded Ring'),
(158,'Armplates of Meteorite Assembly'),
(158,'Boots of Stolen Comet Speed'),
(158,'Copy of The Excalibur'),
(158,'Exact Copy of The Excalibur'),
(158,'Gauntlets of Star Confabulation'),
(158,'Moon Watcher Helmet'),
(158,'Overcoat of the Firmament'),
(158,'Shoulderpads of Asteroid Calling'),
(158,'Vest of Torpid Sunrays'),
(159,'Finely Refined Notum'),
(160,'Bellum Badonis Armor Boots'),
(160,'Bellum Badonis Armor Gloves'),
(160,'Bellum Badonis Armor Helmet'),
(160,'Bellum Badonis Armor Sleeves'),
(160,'Bellum Badonis Body Armor'),
(160,'Bellum Badonis Coat'),
(160,'Bellum Badonis Shoulderpads'),
(160,'Lava capsule'),
(161,'Armplates of Meteorite Assembly'),
(161,'Boots of Stolen Comet Speed'),
(161,'Gauntlets of Star Confabulation'),
(161,'Moon Watcher Helmet'),
(161,'Overcoat of the Firmament'),
(161,'Shoulderpads of Asteroid Calling'),
(161,'Vest of Torpid Sunrays'),
(162,'Virgo''s Analytical Spirit Helper'),
(162,'Virgo''s Arrow Guide'),
(162,'Virgo''s Modest Spirit of Faith'),
(162,'Virgo''s Practical Spirit Helper'),
(163,'Problem Avoiding Device'),
(163,'Problem Seeking Device'),
(163,'Problem Solving Device'),
(164,'Predator Armband'),
(164,'Predator Armor Boots'),
(164,'Predator Armor Facemask'),
(164,'Predator Armor Gloves'),
(164,'Predator Armor Pants'),
(164,'Predator Armor Vest'),
(164,'Predator''s Circlet'),
(165,'Spirit Ring of Self-Education'),
(165,'Spirit Training Program'),
(166,'Xark''s Whisker'),
(167,'Gelid Blade of Inobak'),
(167,'Frost Shard'),
(168,'Permafrost'),
(168,'Abyssal Desecrator'),
(168,'Impious Dominator'),
(168,'Ichor of the Immortal One'),
(168,'Ichor of the Immortal One'),
(168,'Mnemonic Fragment'),
(168,'Constrained Gridspace Waveform'),
(168,'Bloodseal of the Infernal Tyrant'),
(168,'Charred Abaddon Chassis'),
(168,'Third Circle of the Inner Sanctum'),
(169,'Might of the Revenant'),
(169,'Bloodseal of the Infernal Tyrant'),
(169,'Mnemonic Fragment'),
(170,'Corrupted Flesh'),
(170,'Mnemonic Fragment'),
(170,'Skull of Misery'),
(170,'Skull of Despair'),
(170,'Ring of Putrescent Flesh'),
(170,'Teachings of the Immortal One'),
(170,'Charred Abaddon Chassis'),
(170,'Third Circle of the Inner Sanctum'),
(171,'Might of the Revenant'),
(171,'Mnemonic Fragment'),
(171,'Abaddon Upgrade: Skill'),
(172,'Maw of the Abyss'),
(172,'Frost-bound Reaper'),
(172,'Jeuru''s Oscillating Ligature'),
(172,'Bloodshed Armband'),
(172,'Inner Sanctum Knowledge (bottom half of key)'),
(172,'Second Circle of the Inner Sanctum'),
(172,'Charred Abaddon Chassis'),
(173,'Inner Sanctum Knowledge (top half of key)'),
(173,'Maw of the Abyss'),
(173,'Frost-bound Reaper'),
(173,'Jeuru''s Oscillating Ligature'),
(173,'Bloodshed Armband'),
(173,'Second Circle of the Inner Sanctum'),
(173,'Charred Abaddon Chassis'),
(174,'JAME Blaster Prototype IV'),
(174,'JAME Blaster Prototype XII'),
(175,'Bellum Badonis Armor Boots'),
(175,'Bellum Badonis Armor Gloves'),
(175,'Bellum Badonis Armor Helmet'),
(175,'Bellum Badonis Armor Sleeves'),
(175,'Bellum Badonis Body Armor'),
(175,'Bellum Badonis Coat'),
(175,'Bellum Badonis Shoulderpads'),
(175,'Codex Clavis'),
(176,'Bellum Badonis Armor Sleeves'),
(176,'Bellum Badonis Shoulderpads'),
(176,'Bellum Badonis Body Armor'),
(176,'Bellum Badonis Coat'),
(176,'Bellum Badonis Armor Helmet'),
(176,'Bellum Badonis Armor Gloves'),
(176,'Bellum Badonis Armor Boots'),
(177,'Bellum Badonis Armor Boots'),
(177,'Bellum Badonis Armor Gloves'),
(177,'Bellum Badonis Armor Helmet'),
(177,'Bellum Badonis Armor Sleeves'),
(177,'Bellum Badonis Shoulderpads'),
(177,'Bellum Badonis Coat'),
(177,'Bellum Badonis Body Armor'),
(178,'Bellum Badonis Armor Boots'),
(178,'Bellum Badonis Armor Gloves'),
(178,'Bellum Badonis Armor Helmet'),
(178,'Bellum Badonis Armor Sleeves'),
(178,'Bellum Badonis Body Armor'),
(178,'Bellum Badonis Coat'),
(178,'Bellum Badonis Shoulderpads'),
(179,'Metal Armlet of the Quartet'),
(180,'Truspace 900 XL - Vision'),
(181,'Snake Tamer Shield'),
(181,'Snake Tamer Guard'),
(182,'Liquid Notum Ring'),
(182,'Nelly''s Chip'),
(183,'Remains of AESA 10'),
(183,'Soft Ring with Fluff'),
(184,'Notum Miner''s Hard Hat'),
(184,'Glimmering Magnetic Ring'),
(185,'Luminous Copper Band'),
(185,'Crystalized Medusa Queen Hippocampus'),
(185,'Mutated Eremite Leg'),
(186,'Ring of the Endless Depths'),
(186,'Lion''s Leather Vest'),
(186,'Lion''s Leather Sleeve'),
(186,'Lion''s Leather Gloves'),
(186,'Lion''s Leather Pants'),
(186,'Lion''s Leather Boots'),
(186,'Thick Leather Wristbands'),
(187,'I am the Eel'),
(187,'Suzerain''s Spiritual Chief Headwear'),
(188,'I am the Bear'),
(188,'Gurgling River Sprite'),
(188,'Expensive Gift from Earth'),
(188,'Suzerain''s Military Chief Headwear'),
(188,'Disco Duck Sunglasses'),
(188,'Funk Flamingo Sunglasses'),
(188,'Electric Boogie Sunglasses'),
(189,'I am the Owl'),
(189,'Advanced Nano Breed Survival Headwear'),
(189,'Chip of the Eight'),
(189,'Suzerain''s Political Chief Headwear'),
(190,'Mutated Eremite Foetus'),
(190,'Smooth Gold Alloy Ring'),
(190,'Lion''s Leather Vest'),
(190,'Lion''s Leather Sleeve'),
(190,'Lion''s Leather Gloves'),
(190,'Lion''s Leather Pants'),
(190,'Lion''s Leather Boots'),
(191,'Hammered Gold Ring'),
(192,'Clan Ring of Salvation'),
(192,'Brood Champion Gauntlets'),
(193,'Professional Marksman''s Kit'),
(193,'Lion''s Leather Vest'),
(193,'Lion''s Leather Sleeve'),
(193,'Lion''s Leather Gloves'),
(193,'Lion''s Leather Pants'),
(193,'Lion''s Leather Boots'),
(194,'Silly Ring'),
(194,'Beefeater''s Merit Board'),
(194,'Captain Lotto''s Merit Board'),
(194,'Omni-Tek Nano Reservoire Merit Board'),
(194,'Merit Board of the Angry Men'),
(194,'Standard Clan Leader Merit Board'),
(194,'Technocrat Merit Board'),
(194,'Merit Board of the Long Distance Runner'),
(194,'Messenger Merit Board'),
(194,'Front Fighter Merit Board'),
(194,'Omni-Tek Shock Trooper Merit Board'),
(194,'Omni-Tek Engineer Corps Merit Board'),
(194,'Merit Board of the Blue Wolf'),
(194,'Merit Board of the Rainbow Chrysanthemum'),
(194,'Metal Fungus Merit Board'),
(194,'Fly Catcher''s Specs'),
(194,'Profiteer''s Helper'),
(194,'The Argument'),
(195,'Cold Snakeskin Sleeve'),
(195,'Philosophical Slither Larvae'),
(196,'Brumal Chest Symbiant of Endurance'),
(197,'Philosophical Slither Larvae'),
(198,'Cold Snakeskin Sleeve'),
(199,'Nippy John Stiletto'),
(200,'Sleeves of Gashing'),
(201,'Ring of Something Extra'),
(202,'Impudent Bracer'),
(203,'Tiny Spider Band'),
(203,'Tiny Spider Band'),
(203,'Tiny Spider Band'),
(204,'Bracelet of Theory'),
(205,'Spirit of Saccelum'),
(206,'Silken Legchopper Gloves'),
(206,'This Axe Belongs to Jack'),
(206,'Supporting Carbonan Holder'),
(206,'Band of Beeswax'),
(206,'Band of Dog Molars'),
(206,'Band of Snake Skin'),
(206,'Band of the Bear Claw'),
(206,'Band of the Frog Tongue'),
(206,'Curl of Weasel Whiskers'),
(206,'Ring of Crawling Ants'),
(206,'Ring of Magpie Tail Feathers'),
(206,'Ring of the Dolphin Spine'),
(206,'Ring of the Falcon Talon'),
(206,'Ring of the Monkey Tail'),
(206,'Ringlet of Black Panther Whiskers'),
(207,'Communication Processing Unit Rack with 8 Empty Slots'),
(207,'Communication Processing Unit ID=TKL'),
(207,'Plaster Circuit - Brawl'),
(207,'Reinforced NCU Component Belt'),
(207,'Cold Ray Orb'),
(207,'Superior Cold Ray Orb'),
(209,'Fork of Ghasap (Lord Version)'),
(209,'Corroded Blade'),
(209,'Dreadful Pitchfork'),
(209,'Corroded Ring'),
(209,'Pattern of Inevitable Death'),
(209,'Pattern of Imminent Death'),
(210,'Ring of the Nucleus Basalis'),
(211,'Ring of the Nucleus Basalis'),
(212,'Ring of the Nucleus Basalis'),
(212,'Belt of Justice'),
(212,'Juggler''s Treat'),
(213,'Severus'' Fusion Sprayer'),
(213,'Severus'' Void Spinner'),
(214,'Bastion of Deimos'),
(214,'Deimos'' Bio-Enhanced Feedback Rifle'),
(215,'Force-effect Vibro Blade'),
(216,'Hellfury Assault Cannon'),
(217,'Hellspinner Shock Cannon'),
(217,'Augmented Cyborg Arm Armor'),
(217,'Augmented Cyborg Boots'),
(217,'Augmented Cyborg Chest Armor'),
(217,'Augmented Cyborg Gloves'),
(217,'Augmented Cyborg Helmet'),
(217,'Augmented Cyborg Leg Armor'),
(218,'Augmented Cyborg Arm Armor'),
(218,'Augmented Cyborg Boots'),
(218,'Augmented Cyborg Chest Armor'),
(218,'Augmented Cyborg Gloves'),
(218,'Augmented Cyborg Helmet'),
(218,'Augmented Cyborg Leg Armor'),
(218,'Immortal Katana'),
(218,'Faded Immortal Katana'),
(218,'Broken Immortal Katana'),
(218,'Improved Immortal Katana'),
(218,'Bonehammer'),
(218,'Internal Anti-Matter Powerplant'),
(218,'Sub-Dermal Vengeance Screen (Left Hand)'),
(218,'Sub-Dermal Vengeance Screen (Right Hand)'),
(219,'Notum Splice'),
(219,'Ring of Eternal Night'),
(220,'Touch of the Gripper'),
(220,'Rockcrusher Gauntlets'),
(221,'Touch of the Gripper'),
(221,'Nematet''s Inner Eye'),
(221,'Ring of Weeping Flesh'),
(221,'Ring of Eternal Night'),
(221,'Temporal Chalice'),
(221,'Barrow Strength'),
(222,'Withered Flesh'),
(222,'Skull of Woe'),
(222,'Barrow Strength'),
(223,'Dark Memories'),
(223,'Memory Loop'),
(223,'Temporal Chalice'),
(223,'Skull of Woe'),
(223,'Skull of Lamentation'),
(223,'Barrow Strength'),
(223,'Ring of Eternal Night'),
(223,'Ring of Memory Loss'),
(224,'Guardian Tank Armor'),
(224,'Guardian Circuit Board'),
(224,'Bracelet of Amplified Sound'),
(224,'Ring of Tattered Flame'),
(225,'Purifying Rod'),
(225,'Fist of Orion'),
(225,'Withered Flesh'),
(225,'Barrow Strength'),
(226,'Stygian Desolator'),
(226,'Purifying Rod'),
(226,'Skull of the Ancient'),
(226,'Holy Book of the Immortal'),
(227,'Keeper''s Vitality'),
(228,'Windcaller Robe'),
(228,'Withered Flesh'),
(228,'Barrow Strength'),
(229,'Small Titan Message Container'),
(229,'FA Super 90 Pannikin'),
(231,'Piercing Evil'),
(232,'Moon Watcher Helmet'),
(232,'Gauntlets of Star Confabulation'),
(234,'Bigot''s Armband of Sacrifice'),
(234,'Bigot''s Earring of Sacrifice'),
(235,'Bigot''s Earring of Sacrifice'),
(237,'Spirit Tech Toolbox'),
(238,'Malodorous Ring'),
(239,'Bellum Badonis Armor Boots'),
(239,'Bellum Badonis Armor Gloves'),
(239,'Bellum Badonis Armor Helmet'),
(239,'Bellum Badonis Armor Sleeves'),
(239,'Bellum Badonis Body Armor'),
(239,'Bellum Badonis Coat'),
(239,'Bellum Badonis Shoulderpads'),
(240,'Mark of the Fisher King'),
(240,'Shoulderpads of Asteroid Calling'),
(241,'Curse of Malahde'),
(242,'Shoulderpads of Asteroid Calling'),
(243,'Gallant Flapper Ribbon'),
(244,'Moon Watcher Helmet'),
(245,'Shopkeeper''s Sharkskin Sleeves'),
(246,'Boots of the Imaginative'),
(248,'Bellum Badonis Armor Boots'),
(248,'Bellum Badonis Armor Gloves'),
(248,'Bellum Badonis Armor Helmet'),
(248,'Bellum Badonis Armor Sleeves'),
(248,'Bellum Badonis Body Armor'),
(248,'Bellum Badonis Coat'),
(248,'Bellum Badonis Shoulderpads'),
(249,'Apprehensive Spirit Pitcher'),
(250,'The Sacrificed Bracelet of Kay'),
(251,'Barrel of Bacam-Xum'),
(252,'Armplates of Meteorite Assembly'),
(252,'Shoulderpads of Asteroid Calling'),
(252,'Overcoat of the Firmament'),
(252,'Boots of Stolen Comet Speed'),
(253,'Mudurlugu'),
(254,'Stinging Louse'),
(255,'Overcoat of the Firmament'),
(255,'Moon Watcher Helmet'),
(255,'Shoulderpads of Asteroid Calling'),
(255,'Copy of The Excalibur'),
(255,'Exact Copy of The Excalibur'),
(256,'Amused Spirit'),
(256,'Boots of Stolen Comet Speed'),
(256,'Pernicious Body Armor'),
(257,'Vest of Torpid Sunrays'),
(257,'Armplates of Meteorite Assembly'),
(257,'Moon Watcher Helmet'),
(257,'Shoulderpads of Asteroid Calling'),
(257,'Gauntlets of Star Confabulation'),
(258,'Base NCU - Type 00 (0/6)'),
(258,'Nanodeck Activation Device'),
(258,'Multi Colored Xan Belt Tuning Device'),
(258,'Green Xan Belt Tuning Device'),
(258,'Xan Weapon Upgrade Device'),
(258,'Xan Defense Merit Board Base'),
(258,'Xan Combat Merit Board Base'),
(258,'Xan Waist Symbiant, Artillery Unit Beta'),
(258,'Xan Waist Symbiant, Control Unit Beta'),
(258,'Xan Waist Symbiant, Extermination Unit Beta'),
(258,'Xan Waist Symbiant, Infantry Unit Beta'),
(258,'Xan Waist Symbiant, Support Unit Beta'),
(258,'Xan Left Arm Symbiant, Artillery Unit Beta'),
(258,'Xan Left Arm Symbiant, Control Unit Beta'),
(258,'Xan Left Arm Symbiant, Extermination Unit Beta'),
(258,'Xan Left Arm Symbiant, Infantry Unit Beta'),
(258,'Xan Left Arm Symbiant, Support Unit Beta'),
(258,'Xan Right Wrist Symbiant, Artillery Unit Beta'),
(258,'Xan Right Wrist Symbiant, Control Unit Beta'),
(258,'Xan Right Wrist Symbiant, Extermination Unit Beta'),
(258,'Xan Right Wrist Symbiant, Infantry Unit Beta'),
(258,'Xan Right Wrist Symbiant, Support Unit Beta'),
(258,'Xan Ocular Symbiant, Artillery Unit Beta'),
(258,'Xan Ocular Symbiant, Control Unit Beta'),
(258,'Xan Ocular Symbiant, Extermination Unit Beta'),
(258,'Xan Ocular Symbiant, Infantry Unit Beta'),
(258,'Xan Ocular Symbiant, Support Unit Beta'),
(258,'Xan Spirit of Right Wrist Offence - Beta'),
(258,'Xan Spirit of Right Wrist Weakness - Beta'),
(258,'Xan Left Limb Spirit of Essence - Beta'),
(258,'Xan Left Limb Spirit of Strength - Beta'),
(258,'Xan Left Limb Spirit of Understanding - Beta'),
(258,'Xan Left Limb Spirit of Weakness - Beta'),
(258,'Xan Midriff Spirit of Essence - Beta'),
(258,'Xan Midriff Spirit of Knowledge - Beta'),
(258,'Xan Midriff Spirit of Strength - Beta'),
(258,'Xan Midriff Spirit of Weakness - Beta'),
(258,'Xan Spirit of Essence - Beta'),
(258,'Xan Spirit of Discerning Weakness - Beta'),
(259,'Base NCU - Type 00 (0/6)'),
(259,'Nanodeck Activation Device'),
(259,'Multi Colored Xan Belt Tuning Device'),
(259,'Green Xan Belt Tuning Device'),
(259,'Xan Weapon Upgrade Device'),
(259,'Xan Defense Merit Board Base'),
(259,'Xan Combat Merit Board Base'),
(259,'Xan Brain Symbiant, Artillery Unit Beta'),
(259,'Xan Brain Symbiant, Control Unit Beta'),
(259,'Xan Brain Symbiant, Extermination Unit Beta'),
(259,'Xan Brain Symbiant, Infantry Unit Beta'),
(259,'Xan Brain Symbiant, Support Unit Beta'),
(259,'Xan Chest Symbiant, Artillery Unit Beta'),
(259,'Xan Chest Symbiant, Control Unit Beta'),
(259,'Xan Chest Symbiant, Extermination Unit Beta'),
(259,'Xan Chest Symbiant, Infantry Unit Beta'),
(259,'Xan Chest Symbiant, Support Unit Beta'),
(259,'Xan Left Hand Symbiant, Artillery Unit Beta'),
(259,'Xan Left Hand Symbiant, Control Unit Beta'),
(259,'Xan Left Hand Symbiant, Extermination Unit Beta'),
(259,'Xan Left Hand Symbiant, Infantry Unit Beta'),
(259,'Xan Left Hand Symbiant, Support Unit Beta'),
(259,'Xan Left Wrist Symbiant, Artillery Unit Beta'),
(259,'Xan Left Wrist Symbiant, Control Unit Beta'),
(259,'Xan Left Wrist Symbiant, Extermination Unit Beta'),
(259,'Xan Left Wrist Symbiant, Infantry Unit Beta'),
(259,'Xan Left Wrist Symbiant, Support Unit Beta'),
(259,'Xan Brain Spirit of Computer Skill - Beta'),
(259,'Xan Brain Spirit of Offence - Beta'),
(259,'Xan Essence Brain Spirit - Beta'),
(259,'Xan Left Hand Spirit of Defence - Beta'),
(259,'Xan Left Hand Spirit of Strength - Beta'),
(259,'Xan Spirit of Left Wrist Defense - Beta'),
(259,'Xan Spirit of Left Wrist Strength - Beta'),
(259,'Xan Heart Spirit of Essence - Beta'),
(259,'Xan Heart Spirit of Knowledge - Beta'),
(259,'Xan Heart Spirit of Strength - Beta'),
(259,'Xan Heart Spirit of Weakness - Beta'),
(259,'Xan Spirit of Clear Thought - Beta'),
(260,'Unknown Mixture'),
(260,'A piece of cloth'),
(260,'Base NCU - Type 00 (0/6)'),
(260,'Nanodeck Activation Device'),
(260,'Multi Colored Xan Belt Tuning Device'),
(260,'Green Xan Belt Tuning Device'),
(260,'Xan Weapon Upgrade Device'),
(260,'Xan Right Arm Symbiant, Artillery Unit Beta'),
(260,'Xan Right Arm Symbiant, Control Unit Beta'),
(260,'Xan Right Arm Symbiant, Extermination Unit Beta'),
(260,'Xan Right Arm Symbiant, Infantry Unit Beta'),
(260,'Xan Right Arm Symbiant, Support Unit Beta'),
(260,'Xan Right Hand Symbiant, Artillery Unit Beta'),
(260,'Xan Right Hand Symbiant, Control Unit Beta'),
(260,'Xan Right Hand Symbiant, Extermination Unit Beta'),
(260,'Xan Right Hand Symbiant, Infantry Unit Beta'),
(260,'Xan Right Hand Symbiant, Support Unit Beta'),
(260,'Xan Feet Symbiant, Artillery Unit Beta'),
(260,'Xan Feet Symbiant, Control Unit Beta'),
(260,'Xan Feet Symbiant, Extermination Unit Beta'),
(260,'Xan Feet Symbiant, Infantry Unit Beta'),
(260,'Xan Feet Symbiant, Support Unit Beta'),
(260,'Xan Right Limb Spirit of Essence - Beta'),
(260,'Xan Right Limb Spirit of Strength - Beta'),
(260,'Xan Right Limb Spirit of Weakness - Beta'),
(260,'Xan Right Hand Defensive Spirit - Beta'),
(260,'Xan Right Hand Strength Spirit - Beta'),
(260,'Xan Spirit of Insight - Right Hand - Beta'),
(260,'Xan Spirit of Feet Defense - Beta'),
(260,'Xan Spirit of Feet Strength - Beta'),
(260,'Xan Spirit of Defense - Beta'),
(260,'Xan Spirit of Essence - Beta'),
(260,'Xan Spirit of Essence Whispered - Beta'),
(260,'Xan Spirit of Knowledge Whispered - Beta'),
(260,'Xan Spirit of Strength Whispered - Beta'),
(260,'Brute''s Gem'),
(260,'Builder''s Gem'),
(260,'Dictator''s Gem'),
(260,'Explorer''s Gem'),
(260,'Hacker''s Gem'),
(260,'Healer''s Gem'),
(260,'Master''s Gem'),
(260,'Merchant''s Gem'),
(260,'Protecter''s Gem'),
(260,'Sniper''s Gem'),
(260,'Spirit''s Gem'),
(260,'Techno Wizard''s Gem'),
(260,'Warrior''s Gem'),
(260,'Worshipper''s Gem'),
(261,'Death''s Door'),
(261,'Vision of Destruction'),
(261,'Vision of Hope');
