DROP TABLE IF EXISTS skill_alias;
CREATE TABLE skill_alias (id INT NOT NULL, name VARCHAR(50) NOT NULL);
INSERT INTO skill_alias (id, name) VALUES (102, '1 Hand Blunt Weapons');
INSERT INTO skill_alias (id, name) VALUES (102, '1HB');
INSERT INTO skill_alias (id, name) VALUES (103, '1 Hand Edged Weapons');
INSERT INTO skill_alias (id, name) VALUES (103, '1HE');
INSERT INTO skill_alias (id, name) VALUES (107, '2 Handed Blunt Weapons');
INSERT INTO skill_alias (id, name) VALUES (107, '2HB');
INSERT INTO skill_alias (id, name) VALUES (105, '2 Handed Edged Weapons');
INSERT INTO skill_alias (id, name) VALUES (105, '2HE');
INSERT INTO skill_alias (id, name) VALUES (277, 'Added to all Defencive Rolls');
INSERT INTO skill_alias (id, name) VALUES (277, 'Added to all Defensive Rolls');
INSERT INTO skill_alias (id, name) VALUES (277, 'AAD');
INSERT INTO skill_alias (id, name) VALUES (276, 'Added to all Offensive Rolls');
INSERT INTO skill_alias (id, name) VALUES (276, 'AAO');
INSERT INTO skill_alias (id, name) VALUES (281, 'Added to Chemical Damage');
INSERT INTO skill_alias (id, name) VALUES (311, 'Added to Cold Damage');
INSERT INTO skill_alias (id, name) VALUES (280, 'Added to Energy Damage');
INSERT INTO skill_alias (id, name) VALUES (316, 'Added to Fire Damage');
INSERT INTO skill_alias (id, name) VALUES (279, 'Added to Melee Damage');
INSERT INTO skill_alias (id, name) VALUES (318, 'Percentage Additional Nano Executing Cost');
INSERT INTO skill_alias (id, name) VALUES (315, 'Added to Nano Damage');
INSERT INTO skill_alias (id, name) VALUES (317, 'Added to Poison Damage');
INSERT INTO skill_alias (id, name) VALUES (278, 'Added to Projectile Damage');
INSERT INTO skill_alias (id, name) VALUES (282, 'Added to Radiation Damage');
INSERT INTO skill_alias (id, name) VALUES (319, 'Percentage Additional Experience');
INSERT INTO skill_alias (id, name) VALUES (137, 'Outdoor Adventuring');
INSERT INTO skill_alias (id, name) VALUES (116, 'Assault Rifle');
INSERT INTO skill_alias (id, name) VALUES (128, 'Biological Metamorphosis');
INSERT INTO skill_alias (id, name) VALUES (128, 'BM');
INSERT INTO skill_alias (id, name) VALUES (152, 'Body Development');
INSERT INTO skill_alias (id, name) VALUES (121, 'Bow Special Attack');
INSERT INTO skill_alias (id, name) VALUES (165, 'Breaking and Entering');
INSERT INTO skill_alias (id, name) VALUES (165, 'B&E');
INSERT INTO skill_alias (id, name) VALUES (93, 'Chemical Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (95, 'Cold Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (161, 'Computer Literacy');
INSERT INTO skill_alias (id, name) VALUES (161, 'CL');
INSERT INTO skill_alias (id, name) VALUES (161, 'CompLit');
INSERT INTO skill_alias (id, name) VALUES (144, 'Dimach (Soul Attack)');
INSERT INTO skill_alias (id, name) VALUES (96, 'Disease and Poison Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (154, 'Dodge Ranged Attacks');
INSERT INTO skill_alias (id, name) VALUES (153, 'Duck Explosions and Thrown Objects');
INSERT INTO skill_alias (id, name) VALUES (126, 'Electrical Engineering');
INSERT INTO skill_alias (id, name) VALUES (92, 'Energy Attack Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (155, 'Evade Close Combat and Martial Art Attacks');
INSERT INTO skill_alias (id, name) VALUES (97, 'Fire Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (109, 'Grenade or Lumping Throwing');
INSERT INTO skill_alias (id, name) VALUES (110, 'Operate Heavy Weapons');
INSERT INTO skill_alias (id, name) VALUES (90, 'Impact and Projectile Weapon Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (140, 'Map Navigation');
INSERT INTO skill_alias (id, name) VALUES (130, 'Matter Creations');
INSERT INTO skill_alias (id, name) VALUES (130, 'MC');
INSERT INTO skill_alias (id, name) VALUES (127, 'Matter Metamorphosis');
INSERT INTO skill_alias (id, name) VALUES (127, 'MM');
INSERT INTO skill_alias (id, name) VALUES (125, 'Mechanical Engineering');
INSERT INTO skill_alias (id, name) VALUES (125, 'ME');
INSERT INTO skill_alias (id, name) VALUES (104, 'Melee Energy Weapons');
INSERT INTO skill_alias (id, name) VALUES (118, 'Melee Weapons Initiative');
INSERT INTO skill_alias (id, name) VALUES (91, 'Melee Attacks and Martial Art Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (114, 'Machine Guns and Sub Machine Guns');
INSERT INTO skill_alias (id, name) VALUES (134, 'Multiple Ranged Weapons');
INSERT INTO skill_alias (id, name) VALUES (134, 'MR');
INSERT INTO skill_alias (id, name) VALUES (149, 'Nano Execution Init');
INSERT INTO skill_alias (id, name) VALUES (132, 'Nano Energy Pool');
INSERT INTO skill_alias (id, name) VALUES (160, 'Nano-Bot Programming');
INSERT INTO skill_alias (id, name) VALUES (168, 'Nano Resistance');
INSERT INTO skill_alias (id, name) VALUES (136, 'Perception and Spotting');
INSERT INTO skill_alias (id, name) VALUES (159, 'Pharmacological Technology');
INSERT INTO skill_alias (id, name) VALUES (120, 'Physical Prowess and Martial Arts Initiative');
INSERT INTO skill_alias (id, name) VALUES (106, 'Piercing Weapons');
INSERT INTO skill_alias (id, name) VALUES (129, 'Psychological Modifications');
INSERT INTO skill_alias (id, name) VALUES (129, 'PM');
INSERT INTO skill_alias (id, name) VALUES (684, 'PVP Duel Score');
INSERT INTO skill_alias (id, name) VALUES (157, 'Quantum Force field Technology');
INSERT INTO skill_alias (id, name) VALUES (157, 'QFT');
INSERT INTO skill_alias (id, name) VALUES (94, 'Radiation Armor-Class');
INSERT INTO skill_alias (id, name) VALUES (133, 'Ranged Energy Weapons');
INSERT INTO skill_alias (id, name) VALUES (119, 'Ranged Weapons Initiative');
INSERT INTO skill_alias (id, name) VALUES (381, 'RangeIncreaserNF');
INSERT INTO skill_alias (id, name) VALUES (380, 'RangeIncreaserWeapon');
INSERT INTO skill_alias (id, name) VALUES (113, 'Rifle and Sniper-Rifle');
INSERT INTO skill_alias (id, name) VALUES (122, 'Sensory Improvement and Modification');
INSERT INTO skill_alias (id, name) VALUES (122, 'SI');
INSERT INTO skill_alias (id, name) VALUES (108, 'Knife or Sharp Object Throwing');
INSERT INTO skill_alias (id, name) VALUES (146, 'Sneak Attack');
INSERT INTO skill_alias (id, name) VALUES (131, 'Time and Space Alteration');
INSERT INTO skill_alias (id, name) VALUES (131, 'TS');
INSERT INTO skill_alias (id, name) VALUES (135, 'Trap Disarmament');
INSERT INTO skill_alias (id, name) VALUES (139, 'Vehicle Navigation, Airborne');
INSERT INTO skill_alias (id, name) VALUES (166, 'Vehicle Navigation, Ground');
INSERT INTO skill_alias (id, name) VALUES (117, 'Vehicle Navigation, Water');
INSERT INTO skill_alias (id, name) VALUES (158, 'Weapon Smithing');
INSERT INTO skill_alias (id, name) VALUES (16, 'STR');
INSERT INTO skill_alias (id, name) VALUES (17, 'AGI');
INSERT INTO skill_alias (id, name) VALUES (17, 'AGL');
INSERT INTO skill_alias (id, name) VALUES (18, 'STA');
INSERT INTO skill_alias (id, name) VALUES (19, 'INT');
INSERT INTO skill_alias (id, name) VALUES (20, 'SEN');
INSERT INTO skill_alias (id, name) VALUES (21, 'PSY');
INSERT INTO skill_alias (id, name) VALUES (151, 'AS');