DROP TABLE IF EXISTS skill_alias;
CREATE TABLE skill_alias (
	id INT NOT NULL,
	name VARCHAR(50) NOT NULL
);
INSERT INTO skill_alias (id, name) VALUES
(102, '1 Hand Blunt Weapons'),
(102, '1HB'),
(103, '1 Hand Edged Weapons'),
(103, '1HE'),
(107, '2 Handed Blunt Weapons'),
(107, '2HB'),
(105, '2 Handed Edged Weapons'),
(105, '2HE'),
(277, 'Added to all Defencive Rolls'),
(277, 'Added to all Defensive Rolls'),
(277, 'AAD'),
(276, 'Added to all Offensive Rolls'),
(276, 'AAO'),
(281, 'Added to Chemical Damage'),
(311, 'Added to Cold Damage'),
(280, 'Added to Energy Damage'),
(316, 'Added to Fire Damage'),
(279, 'Added to Melee Damage'),
(318, 'Percentage Additional Nano Executing Cost'),
(315, 'Added to Nano Damage'),
(317, 'Added to Poison Damage'),
(278, 'Added to Projectile Damage'),
(282, 'Added to Radiation Damage'),
(319, 'Percentage Additional Experience'),
(137, 'Outdoor Adventuring'),
(116, 'Assault Rifle'),
(128, 'Biological Metamorphosis'),
(128, 'BM'),
(152, 'Body Development'),
(121, 'Bow Special Attack'),
(165, 'Breaking and Entering'),
(165, 'B&E'),
(93, 'Chemical Armor-Class'),
(95, 'Cold Armor-Class'),
(161, 'Computer Literacy'),
(161, 'CL'),
(161, 'CompLit'),
(144, 'Dimach (Soul Attack)'),
(96, 'Disease and Poison Armor-Class'),
(154, 'Dodge Ranged Attacks'),
(153, 'Duck Explosions and Thrown Objects'),
(126, 'Electrical Engineering'),
(92, 'Energy Attack Armor-Class'),
(155, 'Evade Close Combat and Martial Art Attacks'),
(97, 'Fire Armor-Class'),
(109, 'Grenade or Lumping Throwing'),
(110, 'Operate Heavy Weapons'),
(90, 'Impact and Projectile Weapon Armor-Class'),
(140, 'Map Navigation'),
(130, 'Matter Creations'),
(130, 'MC'),
(127, 'Matter Metamorphosis'),
(127, 'MM'),
(125, 'Mechanical Engineering'),
(125, 'ME'),
(104, 'Melee Energy Weapons'),
(118, 'Melee Weapons Initiative'),
(91, 'Melee Attacks and Martial Art Armor-Class'),
(114, 'Machine Guns and Sub Machine Guns'),
(134, 'Multiple Ranged Weapons'),
(134, 'MR'),
(149, 'Nano Execution Init'),
(132, 'Nano Energy Pool'),
(160, 'Nano-Bot Programming'),
(168, 'Nano Resistance'),
(136, 'Perception and Spotting'),
(159, 'Pharmacological Technology'),
(120, 'Physical Prowess and Martial Arts Initiative'),
(106, 'Piercing Weapons'),
(129, 'Psychological Modifications'),
(129, 'PM'),
(684, 'PVP Duel Score'),
(157, 'Quantum Force field Technology'),
(157, 'QFT'),
(94, 'Radiation Armor-Class'),
(133, 'Ranged Energy Weapons'),
(119, 'Ranged Weapons Initiative'),
(381, 'RangeIncreaserNF'),
(380, 'RangeIncreaserWeapon'),
(113, 'Rifle and Sniper-Rifle'),
(122, 'Sensory Improvement and Modification'),
(122, 'SI'),
(108, 'Knife or Sharp Object Throwing'),
(146, 'Sneak Attack'),
(131, 'Time and Space Alteration'),
(131, 'TS'),
(135, 'Trap Disarmament'),
(139, 'Vehicle Navigation, Airborne'),
(166, 'Vehicle Navigation, Ground'),
(117, 'Vehicle Navigation, Water'),
(158, 'Weapon Smithing'),
(16, 'STR'),
(17, 'AGI'),
(17, 'AGL'),
(18, 'STA'),
(19, 'INT'),
(20, 'SEN'),
(21, 'PSY'),
(151, 'AS'),
(100, 'MA');