FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex \
	&& sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -yq --no-install-recommends \
		build-essential \
		cdbs \
		devscripts \
		equivs \
		fakeroot \
		curl \
		software-properties-common \
		dh-systemd \
	&& apt-get clean \
	&& rm -rf /tmp/* /var/tmp/*
RUN touch /.dockerenv
COPY build-package.sh /build-package.sh
