FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex \
	&& sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -yq --no-install-recommends software-properties-common \
		build-essential \
		cdbs \
		devscripts \
		equivs \
		fakeroot \
		curl \
		php-cli \
		php-sqlite3 \
		php-curl \
		php-mysql \
		php-mbstring \
		php-bcmath \
		php-xml \
		php-zip \
		unzip \
	&& apt-get clean \
	&& rm -rf /tmp/* /var/tmp/*
RUN touch /.dockerenv && mkdir /build && chmod 0777 /build
COPY build-package.sh /build-package.sh
ENTRYPOINT ["/build-package.sh"]
