FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex \
	&& sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -yq --no-install-recommends software-properties-common \
	&& add-apt-repository ppa:ondrej/php \
	&& apt-get install -yq --no-install-recommends \
		build-essential \
		cdbs \
		devscripts \
		equivs \
		fakeroot \
		curl \
		php8.0-cli \
		php8.0-sqlite3 \
		php8.0-curl \
		php8.0-mysql \
		php8.0-mbstring \
		php8.0-bcmath \
		php8.0-xml \
		php8.0-zip \
		unzip \
		dh-systemd \
	&& apt-get clean \
	&& rm -rf /tmp/* /var/tmp/*
RUN touch /.dockerenv && mkdir /build && chmod 0777 /build
COPY build-package.sh /build-package.sh
ENTRYPOINT ["/build-package.sh"]
