name: Check coding standards
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run style checker
        shell: bash
        run: |
          composer install -q
          composer dumpautoload
          "$(composer config vendor-dir)/bin/phpcs" --standard=style/Nadybot/ruleset.xml src
