name: Build and push docker image
on:
  push:
    branches:
      - unstable
      - stable
      - multi-platform-docker
    tags:
      - '*'
jobs:
  build:
    name: Create docker image
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout sources
          uses: actions/checkout@v2.2.0
          with:
            fetch-depth: 0
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to registries
          shell: bash
          run: |
            echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io/nadyita
            echo "${{ secrets.GHCR_PAT }}" | docker login -u nadyita --password-stdin ghcr.io
        - name: Get the version
          id: vars
          shell: bash
          run: |
            SRC_VERSION=$(grep -o -P '(?<=const VERSION = ")([^"]+)' src/Core/BotRunner.php)
            TAG=$((git tag -l | grep -v nightly; echo "${SRC_VERSION}") | sed '/-/!{s/$/_/}'| sort -V | sed 's/_$//' | tail -n 1)
            BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            if [ "${BRANCH}" != "stable" ]; then
              VERSION="${TAG}@${BRANCH}"
              TAG="${BRANCH}"
            elif [ "${TAG}" != "$(git describe --tags)" ]; then
              VERSION="${TAG}@${BRANCH}"
              TAG="${BRANCH}"
            else
              VERSION="${TAG}"
            fi
            echo ::set-output name=tag::$(echo ${TAG})
            echo ::set-output name=version::$(echo ${VERSION})
            echo ::set-output name=branch::$(echo ${BRANCH})
        - name: Build the tagged Docker PHP 8.0 image
          shell: bash
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --build-arg VERSION="${{steps.vars.outputs.version}}" \
              --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.tag}}" \
              --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.branch}}" \
              --tag "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.tag}}" \
              --tag "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.branch}}" . && \
            docker buildx build --load \
              --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.tag}}" \
              --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.branch}}" \
              --tag "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.tag}}" \
              --tag "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.branch}}" \
              --builder=container .
        - name: Push the tagged PHP 8.0 Docker image
          shell: bash
          run: |
            docker push "quay.io/nadyita/nadybot:${{steps.vars.outputs.tag}}"
            docker push "quay.io/nadyita/nadybot:${{steps.vars.outputs.branch}}"
            docker push "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.tag}}"
            docker push "ghcr.io/nadybot/nadybot:${{steps.vars.outputs.branch}}"
        - name: Build the tagged Docker-big PHP 8.0 image
          shell: bash
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile-big --build-arg VERSION="${{steps.vars.outputs.version}}" \
              --tag "quay.io/nadyita/nadybot-big:${{steps.vars.outputs.tag}}" \
              --tag "quay.io/nadyita/nadybot-big:${{steps.vars.outputs.branch}}" \
              --tag "ghcr.io/nadybot/nadybot-big:${{steps.vars.outputs.tag}}" \
              --tag "ghcr.io/nadybot/nadybot-big:${{steps.vars.outputs.branch}}" .
        - name: Push the tagged PHP 8.0 Docker-big image
          shell: bash
          run: |
            docker push "quay.io/nadyita/nadybot-big:${{steps.vars.outputs.tag}}"
            docker push "quay.io/nadyita/nadybot-big:${{steps.vars.outputs.branch}}"
            docker push "ghcr.io/nadybot/nadybot-big:${{steps.vars.outputs.tag}}"
            docker push "ghcr.io/nadybot/nadybot-big:${{steps.vars.outputs.branch}}"
        - name: Build the tagged Docker-big-debug PHP 8.0 image
          shell: bash
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile-big --build-arg PROXY_IMAGE=debug --build-arg VERSION="${{steps.vars.outputs.version}}" \
              --tag "quay.io/nadyita/nadybot-big-debug:${{steps.vars.outputs.tag}}" \
              --tag "quay.io/nadyita/nadybot-big-debug:${{steps.vars.outputs.branch}}" \
              --tag "ghcr.io/nadybot/nadybot-big-debug:${{steps.vars.outputs.tag}}" \
              --tag "ghcr.io/nadybot/nadybot-big-debug:${{steps.vars.outputs.branch}}" .
        - name: Push the tagged PHP 8.0 Docker-big-debug image
          shell: bash
          run: |
            docker push "quay.io/nadyita/nadybot-big-debug:${{steps.vars.outputs.tag}}"
            docker push "quay.io/nadyita/nadybot-big-debug:${{steps.vars.outputs.branch}}"
            docker push "ghcr.io/nadybot/nadybot-big-debug:${{steps.vars.outputs.tag}}"
            docker push "ghcr.io/nadybot/nadybot-big-debug:${{steps.vars.outputs.branch}}"

