name: Build and push docker image
on:
  push:
    branches:
      - unstable
      - stable
      - new-build-action
    tags:
      - '*'
jobs:
  build:
    name: Create docker image
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout sources
          uses: actions/checkout@v2.2.0
          with:
            fetch-depth: 0
        - name: Login to Quay Registry
          shell: bash
          run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io/nadyita
        - name: Get the version
          id: vars
          shell: bash
          run: |
            TAG=$(git describe --tags --abbrev=0)
            VERSION="${TAG}"
            BRANCH="${GITHUB_REF:10}"
            if [ "${VERSION}" != "$(git describe --tags --abbrev=1)" ]; then
              VERSION="${VERSION}@${GITHUB_REF:10}"
              TAG="${GITHUB_REF:10}"
            fi
            echo ::set-output name=tag::$(echo ${TAG})
            echo ::set-output name=version::$(echo ${VERSION})
            echo ::set-output name=branch::$(echo ${BRANCH})
        - name: Build the tagged Docker image
          shell: bash
          run: docker build --file Dockerfile --build-arg VERSION="${{steps.vars.outputs.version}}" --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.tag}}" --tag "quay.io/nadyita/nadybot:${{steps.vars.outputs.branch}}" .
        - name: Push the tagged Docker image
          shell: bash
          run: |
            docker push "quay.io/nadyita/nadybot:${{steps.vars.outputs.tag}}"
            docker push "quay.io/nadyita/nadybot:${{steps.vars.outputs.branch}}"

