name: Check static code analysis
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run style checker
        shell: bash
        run: |
          composer install -q
          composer dumpautoload
          "$(composer config vendor-dir)/bin/phpstan" --no-progress -n --no-ansi
