name: Check static code analysis
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.17
          coverage: none
          extensions: sqlite3, sockets, pdo_sqlite, pdo_mysql
      - name: Run style checker
        shell: bash
        run: |
          composer install -q
          composer dumpautoload
          "$(composer config vendor-dir)/bin/phpstan.phar" --no-progress -n --no-ansi
