name: Test migrations
on: [push]

jobs:
  tests:
    name: Test database migrations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1]
        from: [budabot4.db budabot4.mysql]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: sqlite3, sockets, pdo_sqlite, pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Migrate SQLite
        if: endsWith(matrix.from, '.db')
        shell: bash
        run: |
          curl --user "github:${{ secrets.CONFIG_PASSWORD }}" "https://confs.nadybot.org/${{ matrix.from }}" -o data/nadybot.db
          curl --user "github:${{ secrets.CONFIG_PASSWORD }}" "https://confs.nadybot.org/sqlite.php" -o conf/config.php
          php main.php --setup-only --migration-errors-fatal conf/config.php

      - uses: mirromutth/mysql-action@v1.1
        if: endsWith(matrix.from, '.mysql')
        name: Start MySQL server
        with:
          mysql version: '5.6'
          mysql database: 'budabot'
          mysql user: 'budabot'
          mysql password: '123456'

      - name: Migrate MySQL
        if: endsWith(matrix.from, '.mysql')
        shell: bash
        run: |
          curl --user "github:${{ secrets.CONFIG_PASSWORD }}" "https://confs.nadybot.org/${{ matrix.from }}" -o data/nadybot.sql
          curl --user "github:${{ secrets.CONFIG_PASSWORD }}" "https://confs.nadybot.org/mysql.php" -o conf/config.php
          mysql -h 127.0.0.1 -u budabot -p123456 budabot < data/nadybot.sql
          php main.php --setup-only --migration-errors-fatal conf/config.php